// ================================================================
// max/gen_includes.js — GENERATED by scripts/gen-max-include.js
// DO NOT EDIT BY HAND. Source of truth: src/osc-schema.ts,
// src/swam-mapping.ts, src/face-gesture.ts. Regenerate via:
//     npm run gen:max
// ================================================================

// ---------------- OSC addresses (/xk/* and /gan/*) ----------------
var OSC = {
  GROUP_K: "/xk/group/k",
  GROUP_C: "/xk/group/c",
  VERTEX: "/xk/vertex/",
  COMPLEX: "/xk/complex/",
  PATH: "/xk/path",
  CYCLE: "/xk/cycle",
  TETRA: "/xk/tetra",
  SIEVE: "/xk/sieve",
  GYRO: "/xk/gyro",
  PERM: "/xk/perm",
  STEP: "/xk/step",
  ACTIVE: "/xk/active",
  SNAP_ELEMENT: "/xk/snap/element",
  SNAP_QUAT: "/xk/snap/quat",
  SNAP_DEV: "/xk/snap/dev",
  SCRAMBLE: "/xk/scramble",
  SOLVE: "/xk/solve",
  RATE: "/xk/rate",
  REGIME: "/xk/regime",
  EXPR_TILT: "/xk/expr/tilt",
  EXPR_SPIN: "/xk/expr/spin",
  EXPR_DEV: "/xk/expr/dev",
  EXPR_SCRAMBLE: "/xk/expr/scramble",
  ALGORITHM: "/xk/algorithm",
  FACE: "/xk/face",
  VOICE: "/xk/voice",
  PANIC: "/xk/panic",
  TREM_LEARN: "/xk/tremLearn",
  MIDI_NOTEON: "/xk/midi/noteon",
  MIDI_NOTEOFF: "/xk/midi/noteoff",
  MIDI_PANIC: "/xk/midi/panic",
  MIDI_BENDSTEP: "/xk/midi/bendstep",
  GAN_TURN: "/gan/turn",
  GAN_GYRO: "/gan/gyro"
};

// ---------------- SWAM technique enums ---------------------------
var HARMONICS = {
  OFF: 0,
  OCT: 1,
  OCT_5TH: 2,
  CTRL: 3
};

var TREMOLO = {
  OFF: 0,
  SLOW: 1,
  FAST: 2
};

var BOW_POLY = {
  MONO_STRING_CROSSING: 0,
  MONO_POLY_RELEASE: 1,
  DOUBLE: 2,
  DOUBLE_HOLD: 3,
  AUTO: 4
};

// ---------------- Selector CC band centers (0..127) --------------
var HARMONICS_CC_VAL = {
  "0": 16,
  "1": 48,
  "2": 80,
  "3": 112
};

var TREMOLO_CC_VAL = {
  "0": 21,
  "1": 64,
  "2": 106
};

var BOW_POLY_CC_VAL = {
  "0": 12,
  "1": 38,
  "2": 64,
  "3": 89,
  "4": 115
};

// ---------------- Intensity → Expr/Vel/Bow/Density/Trem ---------
var INTENSITY_MAP = {
  p: {
    expr: 20,
    vel: 35,
    bowMult: 0.7,
    density: 0.6,
    tremRateMult: 0.85
  },
  mp: {
    expr: 38,
    vel: 50,
    bowMult: 0.85,
    density: 0.8,
    tremRateMult: 0.92
  },
  mf: {
    expr: 55,
    vel: 68,
    bowMult: 1,
    density: 1,
    tremRateMult: 1
  },
  f: {
    expr: 75,
    vel: 85,
    bowMult: 1.15,
    density: 1.2,
    tremRateMult: 1.08
  },
  ff: {
    expr: 95,
    vel: 100,
    bowMult: 1.3,
    density: 1.4,
    tremRateMult: 1.15
  },
  fff: {
    expr: 115,
    vel: 120,
    bowMult: 1.45,
    density: 1.7,
    tremRateMult: 1.22
  }
};

// ---------------- Envelope profiles (per-note + per-phrase) ------
var ENV_PROFILE = {
  pluck: {
    peakMult: 1,
    attackMult: 0.3,
    releaseMult: 0.7,
    attackCoef: 1.2,
    peakCoef: 0.9,
    sustainCoef: 0.2,
    countMult: 1,
    isSingle: true,
    isDrone: false,
    velCurve: "flat"
  },
  stab: {
    peakMult: 1.15,
    attackMult: 0.15,
    releaseMult: 0.6,
    attackCoef: 1.4,
    peakCoef: 1,
    sustainCoef: 0.25,
    countMult: 1,
    isSingle: true,
    isDrone: false,
    velCurve: "accent-first"
  },
  swell: {
    peakMult: 0.9,
    attackMult: 2,
    releaseMult: 1.3,
    attackCoef: 0.4,
    peakCoef: 0.95,
    sustainCoef: 1,
    countMult: 1,
    isSingle: false,
    isDrone: false,
    velCurve: "cresc"
  },
  drone: {
    peakMult: 0.8,
    attackMult: 1.5,
    releaseMult: 1.5,
    attackCoef: 0.6,
    peakCoef: 0.85,
    sustainCoef: 1,
    countMult: 1,
    isSingle: true,
    isDrone: true,
    velCurve: "flat"
  },
  fade: {
    peakMult: 1,
    attackMult: 1,
    releaseMult: 2.2,
    attackCoef: 1.2,
    peakCoef: 1,
    sustainCoef: 0.25,
    countMult: 1,
    isSingle: false,
    isDrone: false,
    velCurve: "dim"
  },
  burst: {
    peakMult: 1.1,
    attackMult: 0.25,
    releaseMult: 0.5,
    attackCoef: 1.2,
    peakCoef: 1,
    sustainCoef: 0.85,
    countMult: 1.8,
    isSingle: false,
    isDrone: false,
    velCurve: "accent-first"
  }
};

// ---------------- Articulation → note-off velocity ---------------
var ART_OFF_VEL = {
  attack: 110,
  sustained: 45,
  release: 30,
  iterative: 95
};

// ---------------- Motion → semitone nudge ------------------------
var MOTION_NUDGE = {
  static: 0,
  up: 2,
  down: -2,
  oscillate: 0
};

// ---------------- 12 face signatures (derived from TS source) ----
var FACE_MAP = {
  U: {
    durationBias: 0.7,
    registerBias: 0.8,
    envelope: "pluck",
    articulation: "attack",
    motion: "up"
  },
  "U'": {
    durationBias: 1.4,
    registerBias: 0.8,
    envelope: "fade",
    articulation: "release",
    motion: "down"
  },
  D: {
    durationBias: 0.6,
    registerBias: -0.8,
    envelope: "stab",
    articulation: "attack",
    motion: "down"
  },
  "D'": {
    durationBias: 1.8,
    registerBias: -0.8,
    envelope: "drone",
    articulation: "sustained",
    motion: "static"
  },
  L: {
    durationBias: 1.3,
    registerBias: 0,
    envelope: "swell",
    articulation: "sustained",
    motion: "up"
  },
  "L'": {
    durationBias: 1.3,
    registerBias: 0,
    envelope: "fade",
    articulation: "release",
    motion: "down"
  },
  R: {
    durationBias: 0.5,
    registerBias: 0,
    envelope: "stab",
    articulation: "attack",
    motion: "static"
  },
  "R'": {
    durationBias: 0.6,
    registerBias: 0,
    envelope: "burst",
    articulation: "iterative",
    motion: "oscillate"
  },
  F: {
    durationBias: 1.2,
    registerBias: 0.3,
    envelope: "swell",
    articulation: "sustained",
    motion: "up"
  },
  "F'": {
    durationBias: 1.2,
    registerBias: 0.3,
    envelope: "swell",
    articulation: "sustained",
    motion: "down"
  },
  B: {
    durationBias: 0.9,
    registerBias: -0.3,
    envelope: "pluck",
    articulation: "attack",
    motion: "static"
  },
  "B'": {
    durationBias: 1.6,
    registerBias: -0.3,
    envelope: "drone",
    articulation: "sustained",
    motion: "oscillate"
  }
};

// ---------------- Gliss (legato/portamento) complexes ------------
var LEGATO_COMPLEX = {
  "2": true,
  "3": true,
  "5": true,
  "6": true,
  "7": true
};

// ---------------- Regime → attack/expr ramp multipliers ----------
var REGIME_ATTACK_MULT = {
  contemplative: 1.2,
  conversational: 1,
  burst: 0.5
};

var REGIME_EXPR_RAMP_MULT = {
  contemplative: 1.5,
  conversational: 1,
  burst: 0.4
};
