{
    "patcher": {
        "fileversion": 1,
        "appversion": {
            "major": 9,
            "minor": 1,
            "revision": 4,
            "architecture": "x64",
            "modernui": 1
        },
        "classnamespace": "box",
        "rect": [ 1030.0, 92.0, 1039.0, 949.0 ],
        "boxes": [
            {
                "box": {
                    "id": "obj-46",
                    "linecount": 2,
                    "maxclass": "comment",
                    "numinlets": 1,
                    "numoutlets": 0,
                    "patching_rect": [ 636.0, 55.0, 150.0, 34.0 ],
                    "text": "markov chains for phrase detection"
                }
            },
            {
                "box": {
                    "id": "obj-44",
                    "maxclass": "comment",
                    "numinlets": 1,
                    "numoutlets": 0,
                    "patching_rect": [ 990.0, 500.5, 150.0, 20.0 ]
                }
            },
            {
                "box": {
                    "id": "obj-13",
                    "maxclass": "newobj",
                    "numinlets": 1,
                    "numoutlets": 0,
                    "patching_rect": [ 452.0, 681.0, 85.0, 22.0 ],
                    "text": "print xk_swam"
                }
            },
            {
                "box": {
                    "id": "obj-34",
                    "maxclass": "message",
                    "numinlets": 2,
                    "numoutlets": 1,
                    "outlettype": [ "" ],
                    "patching_rect": [ 226.5, 116.0, 29.5, 22.0 ],
                    "text": "1"
                }
            },
            {
                "box": {
                    "id": "obj-33",
                    "maxclass": "newobj",
                    "numinlets": 2,
                    "numoutlets": 2,
                    "outlettype": [ "", "" ],
                    "patching_rect": [ 471.0, 140.0, 79.0, 22.0 ],
                    "text": "route running"
                }
            },
            {
                "box": {
                    "bgmode": 0,
                    "border": 0,
                    "clickthrough": 0,
                    "enablehscroll": 0,
                    "enablevscroll": 0,
                    "id": "obj-32",
                    "lockeddragscroll": 0,
                    "lockedsize": 0,
                    "maxclass": "bpatcher",
                    "name": "n4m.monitor.maxpat",
                    "numinlets": 1,
                    "numoutlets": 1,
                    "offset": [ 0.0, 0.0 ],
                    "outlettype": [ "bang" ],
                    "patching_rect": [ 636.0, 186.0, 400.0, 220.0 ],
                    "viewvisibility": 1
                }
            },
            {
                "box": {
                    "id": "obj-31",
                    "maxclass": "newobj",
                    "numinlets": 1,
                    "numoutlets": 0,
                    "patching_rect": [ 554.0, 140.0, 82.0, 22.0 ],
                    "text": "print relay-out"
                }
            },
            {
                "box": {
                    "id": "obj-27",
                    "maxclass": "message",
                    "numinlets": 2,
                    "numoutlets": 1,
                    "outlettype": [ "" ],
                    "patching_rect": [ 258.0, 82.0, 63.0, 22.0 ],
                    "text": "script stop"
                }
            },
            {
                "box": {
                    "id": "obj-20",
                    "maxclass": "message",
                    "numinlets": 2,
                    "numoutlets": 1,
                    "outlettype": [ "" ],
                    "patching_rect": [ 258.0, 58.0, 64.0, 22.0 ],
                    "text": "script start"
                }
            },
            {
                "box": {
                    "id": "obj-14",
                    "maxclass": "comment",
                    "numinlets": 1,
                    "numoutlets": 0,
                    "patching_rect": [ 346.0, 83.0, 150.0, 20.0 ],
                    "text": "relay"
                }
            },
            {
                "box": {
                    "id": "obj-8",
                    "maxclass": "newobj",
                    "numinlets": 1,
                    "numoutlets": 2,
                    "outlettype": [ "", "" ],
                    "patching_rect": [ 258.0, 112.0, 233.0, 22.0 ],
                    "saved_object_attributes": {
                        "autostart": 0,
                        "defer": 0,
                        "watch": 0
                    },
                    "text": "node.script relay-controller.js @autostart 0",
                    "textfile": {
                        "filename": "relay-controller.js",
                        "flags": 0,
                        "embed": 0,
                        "autowatch": 1
                    }
                }
            },
            {
                "box": {
                    "fontface": 0,
                    "fontname": "Arial",
                    "fontsize": 13.0,
                    "id": "obj-36",
                    "maxclass": "number~",
                    "mode": 2,
                    "numinlets": 2,
                    "numoutlets": 2,
                    "outlettype": [ "signal", "float" ],
                    "patching_rect": [ 225.0, 554.0, 59.0, 23.0 ],
                    "sig": 0.0
                }
            },
            {
                "box": {
                    "id": "obj-38",
                    "maxclass": "toggle",
                    "numinlets": 1,
                    "numoutlets": 1,
                    "outlettype": [ "int" ],
                    "parameter_enable": 0,
                    "patching_rect": [ 303.0, 382.0, 24.0, 24.0 ]
                }
            },
            {
                "box": {
                    "fontname": "Arial",
                    "fontsize": 13.0,
                    "id": "obj-39",
                    "maxclass": "message",
                    "numinlets": 2,
                    "numoutlets": 1,
                    "outlettype": [ "" ],
                    "patching_rect": [ 225.0, 383.0, 38.0, 23.0 ],
                    "text": "open"
                }
            },
            {
                "box": {
                    "fontname": "Arial",
                    "fontsize": 13.0,
                    "id": "obj-40",
                    "maxclass": "newobj",
                    "numinlets": 2,
                    "numoutlets": 1,
                    "outlettype": [ "signal" ],
                    "patching_rect": [ 225.0, 522.0, 176.0, 23.0 ],
                    "text": "sfrecord~ 2"
                }
            },
            {
                "box": {
                    "autosave": 1,
                    "bgmode": 0,
                    "border": 0,
                    "clickthrough": 0,
                    "id": "obj-3",
                    "maxclass": "newobj",
                    "numinlets": 2,
                    "numoutlets": 8,
                    "offset": [ 0.0, 0.0 ],
                    "outlettype": [ "signal", "signal", "", "list", "int", "", "", "" ],
                    "patching_rect": [ 92.0, 705.0, 120.0, 22.0 ],
                    "save": [ "#N", "vst~", "loaduniqueid", 0, "SWAM Cello 3", ";" ],
                    "saved_attribute_attributes": {
                        "valueof": {
                            "parameter_invisible": 1,
                            "parameter_longname": "vst~[1]",
                            "parameter_modmode": 0,
                            "parameter_shortname": "vst~[1]",
                            "parameter_type": 3
                        }
                    },
                    "saved_object_attributes": {
                        "parameter_enable": 1,
                        "parameter_mappable": 0
                    },
                    "snapshot": {
                        "filetype": "C74Snapshot",
                        "version": 2,
                        "minorversion": 0,
                        "name": "snapshotlist",
                        "origin": "vst~",
                        "type": "list",
                        "subtype": "Undefined",
                        "embed": 1,
                        "snapshot": {
                            "pluginname": "SWAM Cello 3.vst3info",
                            "plugindisplayname": "SWAM Cello 3",
                            "pluginsavedname": "",
                            "pluginsaveduniqueid": -298341311,
                            "version": 1,
                            "isbank": 0,
                            "isbase64": 1,
                            "blob": "22722.VMjLgjKV...O+fWarAhckI2bo8la8HRLt.iHfTlai8FYo41Y8HRUTYTK3HxO9.BOVMEUy.Ea0cVZtMEcgQWY9vSRC8Vav8lak4Fc9DiM4TiMtXUSGM1UA4hKtXlKt3hKP4hKt3hKtvjdXQ2bD4hKHQTRFkjdP4VPt3hKHYGUoUULL4BStLjKt3hKtPjKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3RP24VUCkzTHcTQD4hK1k2Sy.iQgYFVWkEdMckV0QiUOgFQosjcHIDRqQSLXUWTVoEciY0SnQUQUYDLB4DZ2j1SlYWdhISQVElYPcEY1UkUOgFSEMFdqwVXs0TaHYFVWkEdMckV0QiUOgFQCwDZtflXmQSLYsFLogTdXMzRynVZHYFTWgUaMc0SnQjdXUWUxHldqECVn4BdhUWVFMlLEwlXqkUUYgWSWoUczX0SnwTZKcGRosjcHIDR4sVagk1c5EVZyY0SnQTZHkicCk0YQcUV5slUgsVPnM1Y2Y0XqASZH0DNrElY5QEVzDjPHomKnwzctMUSz31PLcmKnwjcHkVSrwjTLYmbogTcyLzS1kjLg0VRWg0bAgVXmAiUYgCRBQ1ZzXEVwUUaXsFNUE1YqwVXnMyPOYGNwH1aQckV0QiQHkVSFwjc5kFRyQTZHYFSwfUdHM0SnomTLglKBIVZvjFRyQTZHU2LC8jb3DCVw0zQHkGNVMFcQYUVzMlUZQWUV8DZtjFRlomUZo1ZVE1YAcjXuQSLYgCRBwDZtHUXu0DahUWTWMFcqwVXsASZHYGRBgDd3DSXy0zUZMWUGE1YQISX3ASZHYGR3sTN1kmX0UUagoVUrEVaqwVXqQyPOYWQrI1YvDiX4X2PTETRUAUSAIkVpASZHUTQUkEcEwFVxUkQYglKnM1Y2Y0XqASZHY2LBwDZ2f1S23RUPIUQTMkYpYTV3fjTQE0YVoUamESTmsFagglKnM1Y2Y0XqASZHY2LBwDZ2f1S23RUPIUQTMkYpYTV3fjTQE0cwDlLiQEVuQCaHYFVWgkbUcUV3fjPLQmKogTcyLzSPUjZTEDLDgzaQY0SnQEUTM2ZFkkQIcUV2kjPHESQFEFLUY0SnI1TMY2LR0DZ2f1S23RUPIUQTMkYpYTV3fjTQEELVokZiQEVuQCaHYFVWgkbUcUV3fjPLQmKogTcyLzSPUjZTEDLDgzaQY0SnoGUXQWUWgkbQslXqASLgIGNVMUcQYUVn4BZic1cVM1ZvjFR1MiPLg1Mn8zMtTETRUDUSYlZFkENHIDUu8VajQENrE1ZIIDRwTjQgASUV8DZtj1Ryn1TNQiZS4DMhkVS2Q0PNcGTowzcHg2R4X2PTETRUAUSAIkVpASZHcVSwf0TQcEYxUEaHYFVWgkbUcUV3fjPLQmKogTcyLzSPUjZTEDLDgzaQY0SnQjQgoWVToEciYDUmkzUXMWRBgTLEYTXvTkUOglKosjcHg2R4X2PTETRUAUSAIkVpASZHcVTxnkTEYUX1EUUZMWUrgjYXcEVxU0UYgCRB0DctjFR0MyPOAUQpQUPvPDRuEkUOgFQVMld3XTTqE0UYkVTWoUczXTUuAiUYglKnM1Y2Y0XqASZHcGRosjcHg2R4X2PTETRUAUSAIkVpASZHgFNwLlQ3vlXoUkQTcVRWg0bIIDRwTjQgASUV8DZtj1R4QzPLYmKCwjctjFS4Y1PMcmYS0zLHg2R4X2PTETRUAUSAIkVpASZHgFNwLFSqwVV5ETUXgWQVEFZtf1XmcmUisFLogjcyHDSncCZOciKUAkTEQ0TlolQYgCRngUci01T0sVLhsVPUgEdEYUXn4BZic1cVM1ZvjFR1MiTMg1Mn8zMtTETRUDUSYlZFkENHgFV0M1QTUWSWokdqESXzETUXgWQVEFZtf1XmcmUisFLogjcyHES5o1PLYmKCwjcLMkS4wzTNYGVo0DZ2f1S23RUPIUQTMkYpYTV3fDZXU2XsQ0YzXTV0AiQTUWSGQ0YIcEVykjPHESQFEFLUY0SnQTZKYGR3sTN1MDUAkTUP0TPRokZvjFRngSLiMUTWgEdQcDUmkzUXMWRBgTLEYTXvTkUOglKosjcHg2R4X2PTETRUAUSAIkVpASZHgFNwL1azDSVSUEagkWRBgTLEYTXvTkUOglKosDLHg2R4X2PTETRUAUSAIkVpASZHoVRFEFR3XTXp0TQigWSUkkbUECV5sVLgQWRBgTLEYTXvTkUOgFQosjcHg2R4X2PTETRUAUSAIkVpASZHo1ZsE1YvXkVoE0ZhcFMwH1aQckV0QSLhglKnM1Y2Y0XqASZHc2LBwDZ2f1S23RUPIUQTMkYpYTV3fjTYcVRGEFMIUUVrcmUYkVTWoUczDSTmsFagglKnM1Y2Y0XqASZHY2LR0DZ2f1S23RUPIUQTMkYpYTV3fjTYMSPsI1ZMIiXugCagglKnM1Y2Y0XqASZHY2LBwDdPMDS14xPLYmKowjclkVS2gUZLECR3sTN1MDUAkTUP0TPRokZvjFRsUULhoWUsI1ZvnWXpUkQTcVRWg0bIIDRwTjQgASUV8DZDk1R1gDdKkicCQUPIUETMEjTZoFLogjaEwlXygCag8VSwD0YqwVXAkjPHESQFEFLUY0Sn4RZKYGR3sTN1MDUAkTUP0TPRokZvjFRtUDahMGNrE1aMESTmsFagITRBgTLEYTXvTkUOglKosjcHg2R4X2PTETRUAUSAIkVpASZH4VQrI1b3vVXu0TLTs1cVkUZQcETn4BZic1cVM1ZvjFR3MiPLg1Mn8zMtTETRUDUSYlZFkENHIjVmkzUgUGMVoUZMUUVxUULXoWRpgjYXcEVxU0UYgCR3wDctjFR0MyPOAUQpQUPvPDRuEkUOglYVgEdvDSXzsVLXkWS5EFcQ0lX0cGaHYFVWgkbUcUV3fjPMQmKogTcyLzSPUjZTEDLDgzaQY0SnYlUXgGLwDFcqECV4UkZgcVRFE1ZQwFRlg0UXIWUWkENHIDSz4RZHU2LC8DTEoFUAACQH8VTV8DZlYEV3ASLgQ2ZwfUdAUEV3UjUgglKnM1Y2Y0XqASZHY2LBwDZ2f1S23RUPIUQTMkYpYTV3fjTZQWTWkEdEECV5sFaisVR5ElLqwVXskjPHESQFEFLUY0Sn4RZKQiKCwjctLDS1wzTMICVowjLlkVSzfDdKkicCQUPIUETMEjTZoFLogzaIICUqcmUYkVTWkkZIIDRwTjQgASUV8DZtj1R1gDdKkicCQUPIUETMEjTZoFLogTbUYUV1kjdgISTToEdUECV5sVLgQWRBgTLEYTXvTkUOglKosjcHg2R4X2PTETRUAUSAIkVpASZHIWUwj0YQISXSM1UXYWRBgTLEYTXvTkUOgFQosjcHg2R4X2PTETRUAUSAIkVpASZHMWQVoEcYASXxU0UgsVRBgTLEYTXvTkUOgld3wDctjFR0MyPOAUQpQUPvPDRuEkUOgldVgEcUcEVxkjdgIyZrEVaIIDRwTjQgASUV8DZtj1R1gDdKkicCQUPIUETMEjTZoFLogzbEwVXvTjQgIDNwL1azDSVSUkLhoWQVoEcznWX5UEaHYFVWgkbUcUV3fjTLQmKogTcyLzSPUjZTEDLDgzaQY0SnomUXkWTWkEdQU0XzUEaHYFVWgkbUcUV3fjPMomKosjcHg2R4X2PTETRUAUSAIkVpASZHMWQwHldUwlXVgiQgACLVkETIISXoUULhk2ZrEVaIIDRwTjQgASUV8DZtj1R1gDdKkicCQUPIUETMEjTZoFLogTcAcUVz0TQig2ZrEVaM0FRlg0UXIWUWkENHIDSzQUZHU2LC8DTEoFUAACQH8VTV8DZtbEVzEDLgoWRBgTLEYTXvTkUOglKosjcHg2R4X2PTETRUAUSAIkVpASZHYWQrElc3XzXTs1QhsVRBgTLEYTXvTkUOgFRosjcHg2R4X2PTETRUAUSAIkVpASZHY2ZFMVZmwFTqQiQYglKnM1Y2Y0XqASZHY2LBwDZ2f1S23RUPIUQTMkYpYTV3fjPh81asQVS3XTVxkjPHESQFEFLUY0Sn4RZKMiKCwjctLDS1I1TLACRS0DLhkGSxfDdKkicCQUPIUETMEjTZoFLogjcqwFY0rVLXcVTxDFT3XTXzjjPHESQFEFLUY0SnQTZKYGR3sTN1MDUAkTUP0TPRokZvjFR1cmUXQCL5ElZUYDUmkzUXMWRBgTLEYTXvTkUOglKosjcHg2R4X2PTETRUAUSAIkVpASZHYGNFEFMAcjV0QiUjAUQrI1YvvFRlg0UXIWUWkENHgGSz4RZHU2LC8DTEoFUAACQH8VTV8DZtHSX3E0UXMWUrEld3XTUuAiUYglKnM1Y2Y0XqASZHc2LBwDZ2f1S23RUPIUQTMkYpYTV3fDZhcFMFkUcvvVTuQSLYsVRsgjYXcEVxU0UYgCRBwDcTkFR0MyPOAUQpQUPvPDRuEkUOgFRWk0Y2Y0T0QSLg8TPGMFZtf1XmcmUisFLogTdyHDSncCZOciKUAkTEQ0TlolQYgCRnI1ZYcUV3kjUS81YsgjYXcEVxU0UYgCRRwzLyHDSncCZOciKUAkTEQ0TlolQYgCRnI1ZYcUV3kjQU8FLVkEZtf1XmcmUisFLogjcyHUSncCZOciKUAkTEQ0TlolQYgCR3IVcIcTVuQSLgAUQrI1YvvFRlg0UXIWUWkENHIDSz4RZHU2LC8DTEoFUAACQH8VTV8DZLczXm0TLXcVTxDVRzXzXqkTaic1cFU0avXUVn4BZic1cVM1ZvjFR2MiPLg1Mn8zMtTETRUDUSYlZFkENHgmX5sVLXE2ZrE1ZMIiXPUDahcFLrgjYXcEVxU0UYgCRBwDcTkFR0MyPOAUQpQUPvPDRuEkUOgFSGMFdqwVXsEzPiACMVkEZtf1XmcmUisFLogTdXk1R1gDdKkicCQUPIUETMEjTZoFLogTdQ0lXuQSLYIUUwHFZtf1XmcmUisFLogjcyHUSncCZOciKUAkTEQ0TlolQYgCR3IldIckVzMVLhkDMFM1ZI01XmcmULglKnM1Y2Y0XqASZHIyLBwDZ2f1S23RUPIUQTMkYpYTV3fDdhoWRWoEciEiXIQiQisVRsM1Y2wFSn4BZic1cVM1ZvjFRxLiPLg1Mn8zMtTETRUDUSYlZFkENHgmX5kzUZQ2XwHVRzXzXqkTaic1cwvDZtf1XmcmUisFLogjLyHDSncCZOciKUAkTEQ0TlolQYgCR3IldIckVzMVLh0DNFk0Z2wFRlg0UXIWUWkENHIDSz4RZHU2LC8DTEoFUAACQH8VTV8DZP0lXqASLgIGNVMUcQYUVn4BZic1cVM1ZvjFR1MiPLg1Mn8zMtTETRUDUSYlZFkENHIzX3UkUgU2cwDFTEwlXmACaHYFVWgkbUcUV3fjPLQmKogTcyLzSPUjZTEDLDgzaQY0SnAUahsFLwDlb3DCU1UkUYoVRBgTLEYTXvTkUOgFUosDMtLDS14xPLYmZS0TdXkWS5wTZLg1Mn8zMtTETRUDUSYlZFkENHg1XqcWLgk1ZFMFMIIDRwTjQgASUV8DZDMjSz4RZHU2LC8DTEoFUAACQH8VTV8DZXckVnkzUXoGNFE0ZAczXtkjPHESQFEFLUY0Sn4RZKoGUS4DMpMkSzH1PNACTowTdHkWSzfDdKkicCQUPIUETMEjTZoFLogTLqwFV3UjQiUWVTgkZUYkTzkjPHESQFEFLUY0SngzTMY2LBwDZ2f1S23RUPIUQTMkYpYTV3fDZi8VRrI1YQISXRUjQisVRBgTLEYTXvTkUOgFToszLlMkSzn1TNMCVo0jdlMUSvnVZMg1Mn8zMtTETRUDUSYlZFkENHg1XukDahcVTxDlTEYzXqkTUXQWTrgjYXcEVxU0UYgCRRwTLyHDSncCZOcyMBI1YIcEVy0TaOcyM3IVcU0VXpUEag01ZrE1ZzLzSyslQY8FLVgkcAckVzMFaOciKWgEdEYUX4QyPOAUQpQUPvPDRuEkUOglb5Q0bqYTVu0DQRglKnM1Y2Y0XqASZHg2LBwDZ2f1S23RUPIUQTMkYpYTV3fjTSETQUAUSYQEVoEkLgg2ZWM0YAcjXuQSLYglKnM1Y2Y0XqASZHY2LBwDZ2f1S23RUPIUQTMkYpYTV3fjTSETQUAUSQslXmQSLhYGNwH1ZIIDRwTjQgASUV8DZtj1R1gDdKkicCQUPIUETMEjTZoFLogzYQczXm0TLZQ0ZGI1ZIIDRwTjQgASUV8DZLk1R1gDdKkicCQUPIUETMEjTZoFLogDZMYjTukTUYkWTEoEdUEiXtgiQgoVRBgTLEYTXvTkUOglKosjdpMkSzn1TNQiXCwzcpkWSwHVdMECR3sTN1MDUAkTUP0TPRokZvjFRnkzUYcVTGo0P3vVX5kjLgI2cVkEdEQzXw0TUYQWSsgjYXcEVxU0UYgCRnwDctjFR0MyPOAUQpQUPvPDRuEkUOgFRrI1ZEYzXt0jdgQWTsIVc2YTXqkzUSUWTVkEZtf1XmcmUisFLogjcyHDSncCZOciKUAkTEQ0TlolQYgCR3g0YYckV50DLXc1cVkEZtf1XmcmUisFLogzcyHDSncCZOciKUAkTEQ0TlolQYgCRRk0LA0lXSEUahIUUwHFTEwlXmACaHYFVWgkbUcUV3fjTLQmKogTcyLzSPUjZTEDLDgzaQY0SnImUYQSSvL1aQICVtUULh8TSFM1YYcUVTkzUXQWSGIFZtf1XmcmUisFLogjcyHDSncCZOciKUAkTEQ0TlolQYgCR3o0ZqICUxrlQik1YVkUdAUEVsUULTIyZFMVZmwFRlg0UXIWUWkENHIDSz4RZHU2LC8DTEoFUAACQH8VTV8DZxEiXVUkQgIUUVE1YA0FRlg0UXIWUWkENHIDSzQUZHU2LC8DTEoFUAACQH8VTV8DZ5YkVokjLgQUUsE1ZyQUVzzDLi8VTxfkaUEiXRUULhsVTsgjYXcEVxU0UYgCRRwDctjFR0MyPOAUQpQUPvPDRuEkUOgldVoUZIISXTUUags1cTk0YI0VXBslLRs1ZxPkLqYzXoclUYkWRBgTLEYTXvTkUOglKosjcHg2R4X2PTETRUAUSAIkVpASZHM2ZFk0aAslX0kkUZIWUrgjYXcEVxU0UYgCRRwDctjFR0MyPOAUQpQUPvPDRuEkUOg1LwDldUEyTrkEaUs1cwDVZqYzXzjjPHESQFEFLUY0SnQTZKYGR3sTN1MDUAkTUP0TPRokZvjFR1UDag8VSrgjYXcEVxU0UYgCRBwDctjFR0MyPOAUQpQUPvPDRuEkUOglKWokdMYjVBUEagoVT5ElLzvFRlg0UXIWUWkENHgFS5MiPLg1Mn8zMtTETRUDUSYlZFkENHIjXuEkLX4VRTkEcQYUU1kjPHESQFEFLUY0SngzPMQmKogTcyLzSPUjZTEDLDgzaQY0Sn4xUZUyax.Uc2YzTqMFagUWS5EFcQ0lX0cGaHYFVWgkbUcUV3fjPLQmKogTcyLzSPUjZTEDLDgzaQY0Sn4hLggWTWg0bMUjXxslQiIUQFM1a3XDUmkzUXMWRBgTLEYTXvTkUOgFUCwDctjFR0MyPOAUQpQUPvPDRuEkUOglKxDFdQcEVyUEagoGNw.kdIcTXn4BZic1cVM1ZvjFR1MiPLg1Mn8zMtTETRUDUSYlZFkENHIjX0kzQicFLVkEcQISXMUjQjQ0ZVE1ZIIDRwTjQgASUV8DZPk1R1gDdKkicCQUPIUETMEjTZoFLogDdUECVqsFaisFLTIEQqoGTtUDagQWUFEFZtf1XmcmUisFLogzchk1R1gDdKkicCQUPIUETMEjTZoFLogDdUYTXqUTLhs1XUoEcQECT0QiQigGNFElbUwlXMgiQYsVRBgTLEYTXvTkUOglKosjcHg2R4X2PTETRUAUSAIkVpASZHkWUxHldEYkVzkjPHESQFEFLUY0Sn4RZKYGR3sTN1MDUAkTUP0TPRokZvjFR4UkLhoWQVoEcIUEVyETaHYFVWgkbUcUV3fjPLQmKogTcyLzSPUjZTEDLDgzaQY0SnAUahcFMwHlc3DiXqkjPHESQFEFLUY0Sn4RZKYGR3sTN1k2R1UDahcFLwHVN1M0TIEEURIUUVE1YAcjXuQSLYQUQrgkbUw1S2nGURQzZpQ0ZvXEV1EzUZQ2XVEEcQ0lXzDjTYQWQrgkbUYTV3fjTLglKBI1YIcEVyUkQisVRWIkZvjFRqc1QhgWUwHVdqESXzkjPHk1YVgEczXUVxASZHcmXogjY5YUV40zUX0VUFUEMAcUV3fjTLglKREVdIY0SnQzTLglKBEVdIY0SnomTLg1LC8TSqQTTIkTUYMWQFIlcqwVXs0DUigWVWkkYpwVX1U0QiUFLVoEcvjFR1MiPLglKRoEcAc0X5gSUgc1YW8DZDkFSxLiPLglK3EFLQIyUysFaggCR3wDctjFRlciUioGNUE1Ymc0SnQTZLAyLBwDZtfmXtUjQhsFLogjcyHDS4o1TNQiZS4DMpMES1Q0TNkmK4wTdHIDR4s1UgMWUFMFdqc0Sn4RZKMiKCwjctLDS1QzTLQCRCwDMHMkSn4BZXQSPWgUdMc0Sn4RZHYFRVokc3XTXmkzUOglKogTcyLzS0oGURQzZpQ0ZvXEV1EzUZQ2XVEEcQ0lXzPyPO0zZDEURIUUVyUjQhY2ZrEVaUoVX5kzUjYFUrE1YIYTXqEkUOgFQogjYtbEV3UjUgsVTWkEdqQTV3fDZi8VRrI1YQISXDUkQho2YrgjYLYjVmQCags1cV8DZDkWSn4hTgsVSxH1YiYUVTs1QhsFLogzcHIDRy0TaXgCRRwDZtHTX4kjUOgldRwDZyLzSMsFQQkTRUk0bEYjX1sFag0VSTMFdYcUVloFagYWUGMVYvXkVzASZHY2LBwDZtHkVzEzUioGNUE1Ymc0SnQTZLIyLBwDZtfWXvDkLWM2ZrEFNHIESz4RZHY1MVMld3TUXmc1UOgFQSwjcyHDSn4Bdh4VQFI1ZvjFR1MiPLglK3IFMvXUXqEUahQCLogjcyHUSn4BZXQSPWgUdMc0Sn4RZHYFRVokc3XTXmkzUOglKogTcyLzS0oGURQzZpQ0ZvXEV1EzUZQ2XVEEcQ0lXzPyPO0zZDEURIUUVyUjQhY2ZrEVaUoVX5kzUjYFUrE1YIYTXqEkUOgFQogjYtbEV3UjUgsVTWkEdqQTV3fDZi8VRrI1YQISXRUjQisVRBgTZmYEVzQiUYIGLogzchkFRlomUYkWSWgUaUYTUzDzUYgCRRwDZtHUX4kjUOgFQS4DZtHTX4kjUOgldRwDZyLzSMsFQQkTRUk0bEYjX1sFag0VSTMFdYcUVloFagYWUGMVYvXkVzASZHY2LBwDZtHkVzEzUioGNUE1Ymc0SnQTZLIyLBwDZtfWXvDkLWM2ZrEFNHIDSz4RZHY1MVMld3TUXmc1UOgFQowjLyHDSn4Bdh4VQFI1ZvjFR1MiPLglK3IFMvXUXqEUahQCLogjcyHUSn4BZXQSPWgUdMc0Sn4RZHYFRVokc3XTXmkzUOglKogTcyLzS0oGURQzZpQ0ZvXEV1EzUZQ2XVEEcQ0lXzPyPO0zZDEURIUUVyUjQhY2ZrEVaUoVX5kzUjYFUrE1YIYTXqEkUOgFQogjYtbEV3UjUgsVTWkEdqQTV3fDZXU2XsEUcIICVqETUXgWQVEFZtfGVtUDagQWUFEFNHIESxfjPHMWUwHVdEESVqEUUjYWUV8DZDkFRloWLhgFLogzchkFRlYWLhgFLogzbDkFR4X2TSkTTTIkTUYUXmEzQh8FMwj0PU0lXwTkQH8FMFIFLQIyUysFaggCRBwDctjFRloFagYWUGMVYvXEVy.SZHcGR40DctjFRlciUioGNUE1azX0Sn4RZKYGRBgTcUczXkAiUXMCLogzcHkWSz4RZHYFSGo0YAcUV3fjPLQmKogjYLcEYyAiUYoWRWQFNHIDSzQUZHYFRVQlcEEiX4ASZHYGRBgDZqYjX0cmUXgGLogjcHg2R4XWdK0zZDEURIUUVyUjQhY2ZrEVaUoVX5kzUjkicSMURQQkTRUkUgcVPGI1azDSVEQiQig2ZGgzZzXEVncmUYoFLogzcHIDR1UDahcFLVkkdUwlXIEkUOgFRwDlLAASX4slQi8FNrEFTEwlXmACaHYFSFo0YzvVXqcmUOgFQ40DZtHUXq0jLhc1XVkEUqcjXqASZHcGRBgzbM0FV3fjTLECRBgjbM0FV3fjTKcGRn8zM5QkTDslZTsFLVgkcAckVzMVLPASRsM1ZAIkVzEzUioGNUE1azX0Sn4RZKYGRBgzazXjXvDkLWMWQFQFNHIES3IVZKYGRBgTcUczXkAiUZQGLogjcyHDSn4BdgASTxb0bEYDY3fjTLgmXosjcHIDR4clUXYWUV8DZtj1R1gjPHk2ZWE1bUYzX3s1UOglKosDLHIDRns1QhcVSxHFNHIDSn4BZX8VPxDlbEwlX3fjPLg1Mn8zM2H0TIEEURIUUVE1YAcjXuQSLYUDMFMFdq01S2nGURQzZpQ0ZvXEV1EzUZQ2XVEEcQ0lXzDjTYQWQrgkbUYTV3fjTLglKBI1YIcEVyUkQisVRWIkZvjFR5kzUYMGNFEVcMUjXqUkQYglK3gkaEwVXzUkQggCRRwDZtHUXq0jLhc1XVkEUqcjXqASZHcGRBgzbM0FV3fjPNYGRBgjbM0FV3fjTKcGRn8zM5QkTDslZTsFLVgkcAckVzMVLPASRsM1ZAIkVzEzUioGNUE1azX0Sn4RZKYGRBgzazXjXvDkLWMWQFQFNHIES3IVZKYGRBgTcUczXkAiUZQGLogjcyHDSn4BdgASTxb0bEYDY3fjTLgmXosjcHIDR4clUXYWUV8DZtj1R1gjPHk2ZWE1bUYzX3s1UOglKosDLHIDRns1QhcVSxHFNHIDSn4BZX8VPxDlbEwlX3fjPLg1Mn8zM2H0TIEEURIUUVE1YAcjXuQSLYUDMFMFdq01S2nGURQzZpQ0ZvXEV1EzUZQ2XVEEcQ0lXzDjTYQWQrgkbUYTV3fjTLglKBI1YIcEVyUkQisVRWIkZvjFRyUjUZQWVvDlbUcUXqkjPHk1YVgEczXUVxASZHcmXogjY5YUV40zUX0VUFUEMAcUV3fjTLglKREVdIY0SnIVZHYlcwHFZvjFRyQTZHkicSMURQQkTRUkUgcVPGI1azDSVCUUahESUFgzazXjXvDkLWM2ZrEFNHIDSz4RZHYlZrElcUczXkAiUXMCLogzcHkWSz4RZHY1MVMld3TUXuQiUOglKosjcHIDR0U0QiUFLVg0LvjFR2gTdMQmKogjYLcjVmEzUYgCRBwDctjFRlwzUjMGLVkkdIcEY3fjPLQGUogjYHYEY1UTLhkGLogjcHIDRnslQhU2cVgEdvjFR1gDdKkic4sTSqQTTIkTUYMWQFIlcqwVXsUkZgoWRWQVN1M0TIEEURIUUVE1YAcjXuQSLYUDMFMFdqcDRqQiUXg1cVkkZvjFR2gjPHYWQrI1YvXUV5UEahkTTV8DZtbEVzEDLgoWRBgTZmYEVzQiUYIGLogzchkFRlomUYkWSWgUaUYTUzDzUYgCRRwDZtHUX4kjUOgFQCwDZtHTX4kjUOgldRwDZyLzSMsFQQkTRUk0bEYjX1sFag0VSTMFdYcUVloFagYWUGMVYvXkVzASZHY2LBwDZtHkVzEzUioGNUE1Ymc0SnQTZLIyLBwDZtfWXvDkLWM2ZrEFNHIDSz4RZHY1MVMld3TUXmc1UOgFQowjLyHDSn4Bdh4VQFI1ZvjFR1MiPLglK3IFMvXUXqEUahQCLogjcyHUSn4BZXQSPWgUdMc0Sn4RZHYFRVokc3XTXmkzUOglKogTcyLzS0oGURQzZpQ0ZvXEV1EzUZQ2XVEEcQ0lXzPyPO0zZDEURIUUVyUjQhY2ZrEVaUoVX5kzUjYFUrE1YIYTXqEkUOgFQogjYtbEV3UjUgsVTWkEdqQTV3fDZhsVVWkEdIY0TucVaHYFSFo0YzvVXqcmUOgFQ40DZtHUXq0jLhc1XVkEUqcjXqASZHcGRBgzbM0FV3fjTNYGRBgjbM0FV3fjTKcGRn8zM5QkTDslZTsFLVgkcAckVzMVLPASRsM1ZAIkVzEzUioGNUE1azX0Sn4RZKYGRBgzazXjXvDkLWMWQFQFNHIES3IVZKYGRBgTcUczXkAiUZQGLogjcyHDSn4BdgASTxb0bEYDY3fjTLgmXosjcHIDR4clUXYWUV8DZtj1R1gjPHk2ZWE1bUYzX3s1UOglKosDLHIDRns1QhcVSxHFNHIDSn4BZX8VPxDlbEwlX3fjPLg1Mn8zM2H0TIEEURIUUVE1YAcjXuQSLYUDMFMFdq01S2nGURQzZpQ0ZvXEV1EzUZQ2XVEEcQ0lXzDjTYQWQrgkbUYTV3fjTLglKBI1YIcEVyUkQisVRWIkZvjFRm0TLXMUTWQlbUwFRlwjQZcFMrE1Z2Y0SnQTdMglKRE1ZMIiXmMlUYQ0ZGI1ZvjFR2gjPHMWSsgENHIESyfjPHIWSsgENHI0R2gDZOcidTIEQqoFUqAiUXYWPWoEciECTvjTaisVPRoEcAc0X5gSUg8FMV8DZtj1R1gjPH8FMFIFLQIyUyUjQjgCRRwDdhk1R1gjPHUWUGMVYvXkVzASZHY2LBwDZtfWXvDkLWMWQFQFNHIES3IVZKYGRBgTdmYEV1UkUOglKosjcHIDR4s1UgMWUFMFdqc0Sn4RZKACRBgDZqcjXm0jLhgCRBwDZtfFVuEjLgIWQrIFNHIDSncCZOcyMRMURQQkTRUkUgcVPGI1azDSVEQiQig2Zs8zM5QkTDslZTsFLVgkcAckVzMlUQQWTsIFMAIUVzUDaXIWUFkENHIESn4hPhcVRWg0bUYzXqkzURoFLogTdUIiX5UjUZQWRBgTZmYEVzQiUYIGLogzchkFRlomUYkWSWgUaUYTUzDzUYgCRRwDZtHUX4kjUOgFVC0DZtHTX4kjUOgldRwDZyLzSMsFQQkTRUk0bEYjX1sFag0VSTMFdYcUVloFagYWUGMVYvXkVzASZHY2LBwDZtHkVzEzUioGNUE1Ymc0SnQTZLIyLBwDZtfWXvDkLWM2ZrEFNHIESz4RZHY1MVMld3TUXmc1UOgFQowjLyHDSn4Bdh4VQFI1ZvjFR1MiTNQiKCwjctLDS1o1TMkGV40jdLkFSn4BdhQCLVE1ZQ0lXz.SZHY2LR0DZtfFVzDzUXkWSW8DZtjFRlgjUZYGNFE1YIc0Sn4RZHU2LC8Tc5QkTDslZTsFLVgkcAckVzMlUQQWTsIFMzLzSMsFQQkTRUk0bEYjX1sFag0VUpEldIcEYlQEagcVRFE1ZQY0SnQTZHYlKWgEdEYUXqE0UYg2ZDkENHIDUu8VajQENrE1ZIIDRoclUXQGMVkkbvjFR2IVZHYldVkUdMcEVsUkQUQSPWkENHIESn4hTgkWRV8DZDkVSn4hPgkWRV8DZ5IESnMyPO0zZDEURIUUVyUjQhY2ZrEVaMQ0X3k0UYYlZrElcUczXkAiUZQGLogjcyHDSn4hTZQWPWMld3TUXmc1UOgFQowjLyHDSn4BdgASTxb0bqwVX3fjPLQmKogjY2X0X5gSUgc1YW8DZDkFSxLiPLglK3IlaEYjXqASZHY2LBwDZtfmXz.iUgsVTsIFMvjFR1MiTMglKngEMAcEV40zUOglKogjYHYkV1giQgcVRW8DZtjFR0MyPOUmdTIEQqoFUqAiUXYWPWoEciYUTzEUahQCMC8TSqQTTIkTUYMWQFIlcqwVXsUkZgoWRWQlYTwVXmkjQgsVTV8DZDkFRl4xUXgWQVE1ZQcUV3sFQYgCRBIVc2YEY1cVLgQ2ZGQ0YIcEVykjPHk1YVgEczXUVxASZHcmXogjY5YUV40zUX0VUFUEMAcUV3fjTLglKREVdIY0SnY1TLglKBEVdIY0SnomTLg1LC8TSqQTTIkTUYMWQFIlcqwVXs0DUigWVWkkYpwVX1U0QiUFLVoEcvjFR1MiPLglKRoEcAc0X5gSUgc1YW8DZDkFSxLiPLglK3EFLQIyUysFaggCRBwDctjFRlciUioGNUE1Ymc0SnQTZLIyLBwDZtfmXtUjQhsFLogjcyHDSn4BdhQCLVE1ZQ0lXz.SZHY2LR0DZtfFVzDzUXkWSW8DZtjFRlgjUZYGNFE1YIc0Sn4RZHU2LC8Tc5QkTDslZTsFLVgkcAckVzMlUQQWTsIFMzLzSMsFQQkTRUk0bEYjX1sFag0VUpEldIcEYlQEagcVRFE1ZQY0SnQTZHYlKWgEdEYUXqE0UYg2ZDkENHIjVmkzUgUGMVoUZMcDUmkzUXMWRBgTZmYEVzQiUYIGLogzchkFRlomUYkWSWgUaUYTUzDzUYgCRRwDZtHUX4kjUOglXC4DZtHTX4kjUOgldRwDZyLzSMsFQQkTRUk0bEYjX1sFag0VSTMFdYcUVloFagYWUGMVYvXkVzASZHY2LBwDZtHkVzEzUioGNUE1Ymc0SnQTZLIyLBwDZtfWXvDkLWM2ZrEFNHIDSz4RZHY1MVMld3TUXmc1UOgFQowjLyHDSn4Bdh4VQFI1ZvjFR1MiPLglK3IFMvXUXqEUahQCLogjcyHUSn4BZXQSPWgUdMc0Sn4RZHYFRVokc3XTXmkzUOglKogTcyLzS0oGURQzZpQ0ZvXEV1EzUZQ2XVEEcQ0lXzPyPO0zZDEURIUUVyUjQhY2ZrEVaUoVX5kzUjYFUrE1YIYTXqEkUOgFQogjYtbEV3UjUgsVTWkEdqQTV3fjPigWUVEVc2ESXPUDahcFLrgjYLYjVmQCags1cV8DZDkFRlomUYkWSWgUaUYTUzDzUYgCRRwDZtHUX4kjUOglXS4DZtHTX4kjUOgldRwDZyLzSMsFQQkTRUk0bEYjX1sFag0VSTMFdYcUVloFagYWUGMVYvXkVzASZHY2LBwDZtHkVzEzUioGNUE1Ymc0SnQTZLIyLBwDZtfWXvDkLWM2ZrEFNHIDSz4RZHY1MVMld3TUXmc1UOgFQowjLyHDSn4Bdh4VQFI1ZvjFR1MiPLglK3IFMvXUXqEUahQCLogjcyHUSn4BZXQSPWgUdMc0Sn4RZHYFRVokc3XTXmkzUOglKogTcyLzS0oGURQzZpQ0ZvXEV1EzUZQ2XVEEcQ0lXzPyPO0zZDEURIUUVyUjQhY2ZrEVaUoVX5kzUjYFUrE1YIYTXqEkUOglKogjYtbEV3UjUgsVTWkEdqQTV3fDZis1cwDVZqYzXzjjPHk1YVgEczXUVxASZHcmXogjY5YUV40zUX0VUFUEMAcUV3fjPMglKREVdIY0SnomTLglKBEVdIY0SnomTLg1LC8TSqQTTIkTUYMWQFIlcqwVXs0DUigWVWkkYpwVX1U0QiUFLVoEcvjFR1MiPLglKRoEcAc0X5gSUgc1YW8DZDkFSxLiPLglK3EFLQIyUysFaggCRRwDctjFRlciUioGNUE1Ymc0SnQTZLIyLBwDZtfmXtUjQhsFLogjcyHDSn4BdhQCLVE1ZQ0lXz.SZHY2LR0DZtfFVzDzUXkWSW8DZDkFRlgjUZYGNFE1YIc0Sn4RZHU2LC8Tc5QkTDslZTsFLVgkcAckVzMlUQQWTsIFMzLzS0oGURQzZpQ0ZvXEV1EzUZQ2XFU0YIYTXqQyPOUmdVokZqYUXmEzQh8FMwjUN1MUXu0DahUWTWMFcqwVXsQyPOYWQrI1YvDiX4X2PTETRUAUSAIkVpASZHM2ZwfEd3XTUvPiUZQ2XrQUc3XzXn4BZic1cVM1ZvjFR1MiPLg1Mn8zMtTETRUDUSYlZFkENHIUXu0DahUWTWMFcqwVXsgSQLglKnM1Y2Y0XqASZHMGUCwDctjFR0MyPOAUQpQUPvPDRuEkUOgldVoUZIISX5UUag8FMwjUYEkFRlg0UXIWUWkENHI0Rv3RZKYGR3sTN1MDUAkTUP0TPRokZvjFRysVLXgGNFMFLzXkVzMVLWcmKogjYXcEVxU0UYgCRRsDLtj1R1gDdKkicCQUPIUETMEjTZoFLogzbqECV3giQiACMVoEciEyU2QTZHYFVWgkbUcUV3fjTKAiKosjcHg2R4X2PTETRUAUSAIkVpASZHM2ZwfEd3XzXvPiUZQ2XwbEdHIDRwTjQgASUV8DZ5IUS1MiPLg1Mn8zMtTETRUDUSYlZFkENHIUXu0DahUWTWMFcqwVXsgCLLglKnM1Y2Y0XqASZHMGUCwDctjFR0MyPOAUQpQUPvPDRuEkUOgldVoUZIISX5UUag8FMwjUYQkFRlg0UXIWUWkENHI0Rv3RZKYGR3sTN1MDUAkTUP0TPRokZvjFRysVLXgGNFMFLzXkVzMVLWACRBgTLEYTXvTkUOgldR0jcyHDSncCZOciKUAkTEQ0TlolQYgCRRE1aMwlX0E0UiQ2ZrEVa3rVSn4BZic1cVM1ZvjFRyQ0PLQmKogTcyLzSPUjZTEDLDgzaQY0SnomUZkVRxDldU0VXuQSLYU1XogjYXcEVxU0UYgCRRsDLtj1R1gDdKkicCQUPIUETMEjTZoFLogzbqECV3giQiACMVoEciEyUyfjPHESQFEFLUY0SnomTMY2LBwDZ2f1S23RUPIUQTMkYpYTV3fjTg8VSrIVcQc0XzsFag0FNU4DZtf1XmcmUisFLogzbTMDSz4RZHU2LC8DTEoFUAACQH8VTV8DZ5YzX4E0UXoWUxHVYAkFRlg0UXIWUWkENHIDSz4RZHU2LC8DTEoFUAACQH8VTV8DZ5YzX4E0UXoWUxHVYEkFRlg0UXIWUWkENHIDSz4RZHU2LC8DTEoFUAACQH8VTV8DZ5YzX4E0UXoWUxHVYEMDSn4BZic1cVM1ZvjFR1MiPLg1Mn8zMtTETRUDUSYlZFkENHIUX50zQicVTWMVd3TES2gjPHESQFEFLUY0Sn4RZKYGR3sTN1MDUAkTUP0TPRokZvjFRyEkLhoWQFMFLMIyU3gjPHESQFEFLUY0Sn4RZKYGR3sTN1MDUAkTUP0TPRokZvjFRyEkLhoWQFMFLMIyU4gjPHESQFEFLUY0Sn4RZKYGR3sTN1MDUAkTUP0TPRokZvjFRyEkLhoWQFMFLMIyU5gjPHESQFEFLUY0Sn4RZKYGR3sTN1MDUAkTUP0TPRokZvjFRyEkLhoWQFMFLMIyUvfjPHESQFEFLUY0Sn4RZKYGR3sTN1MDUAkTUP0TPRokZvjFRyEkLhoWQFMFLMIyUwfjPHESQFEFLUY0Sn4RZKYGR3sTN1MDUAkTUP0TPRokZvjFRyEkLhoWQFMFLMIyUxfjPHESQFEFLUY0Sn4RZKYGR3sTN1MDUAkTUP0TPRokZvjFRyEkLhoWQFMFLMIyUyfjPHESQFEFLUY0Sn4RZKYGR3sTN1MDUAkTUP0TPRokZvjFRyEkLhoWQFMFLMIyUzfjPHESQFEFLUY0Sn4RZKYGR3sTN1MDUAkTUP0TPRokZvjFR5UkUgYWUrI1YvvFRlg0UXIWUWkENHIDSz4RZHU2LC8TctbEV3UjUgkGMC8jcIcUV4UkQikGMC8jcIcUV4UkQiYFSGEVcQ01Tv.CaXsVRW8DZDkFR4XWZgUWTWkkYpYTV3fjPLglK3IldEYzXvzzUOglKogjYXcEVxU0UYgCRRsDLtjFRlMSLgoWUrM0YvXUV3fDdPg1Mn8zMyDSX5UkQH8VTV8DZDkFRlwzQicVTWMVdvjFR1gjPHESQFEFLUY0SnomTMYGRBgDc3XzXqQCUXMWUV8DZLoGRncCZOcyLwDldUYDRuEkUOgFRogjYLczXmE0UikGLogjcHIDRwTjQgASUV8DZ5IUS1gjPHQGNFM1ZzPEVyUkUOgFTpgTcyLzSzgiQisVPRokZvjFR4gjPHkWTWgkdUIiX3fjPLglKnM1Y2Y0XqASZHMGUCwDZtfVX0E0UY4TQVE1ZvjFRD0DZHU2LC8Dc3XzXqEjTZoFLogjdHIDR4E0UXoWUxHFNHIDSn4BZic1cVM1ZvjFRyQ0PLglKnEVcQcUVNUjUgsFLogTQIg2R4XWZgUWTWkkYpYTV3fjTMglK3IldEYzXvzzUOglKogjYXcEVxU0UYgCRRsDLtjFRlMSLgoWUrM0YvXUV3fDZQg1Mn8zMyDSX5UkQH8VTV8DZXkFRlwzQicVTWMVdvjFR1gjPHESQFEFLUY0SnomTMYGRBgDc3XzXqQCUXMWUV8DZXoGRncCZOcyLwDldUYDRuEkUOglXogjYLczXmE0UikGLogjcHIDRwTjQgASUV8DZ5IUS1gjPHQGNFM1ZzPEVyUkUOglXpgTcyLzSzgiQisVPRokZvjFRyfjPHkWTWgkdUIiX3fjPLglKnM1Y2Y0XqASZHMGUCwDZtfVX0E0UY4TQVE1ZvjFRG0DZHU2LC8Dc3XzXqEjTZoFLogDMHIDR4E0UXoWUxHFNHIDSn4BZic1cVM1ZvjFRyQ0PLglKnEVcQcUVNUjUgsFLogTPIg2R4XWZgUWTWkkYpYTV3fjTLYGRBgTdQcEV5UkLhgCRBwDZtf1XmcmUisFLogzbTMDSn4BZgUWTWkkSEYUXqASZHETSngTcyLzSzgiQisVPRokZvjFR2QTZHYFSGM1YQc0X4ASZHYGRBgTLEYTXvTkUOgldR0jcHIDRzgiQisFMTg0bUY0SngjZHU2LC8TctzlXq0zUYoGMC8jcIcUV4UkQiYFSGEVcQ01Tv.CaXsVRW8DZHkFR4XWZgUWTWkkYpYTV3fjPLglK3IldEYzXvzzUOglKogjYXcEVxU0UYgCRRsDLtjFRlMSLgoWUrM0YvXUV3fDdPg1Mn8zMyDSX5UkQH8VTV8DZDkFRlwzQicVTWMVdvjFR1gjPHESQFEFLUY0SnomTMYGRBgDc3XzXqQCUXMWUV8DZLoGRncCZOcyLwDldUYDRuEkUOgFRogjYLczXmE0UikGLogjcHIDRwTjQgASUV8DZ5IUS1gjPHQGNFM1ZzPEVyUkUOgFTpgTcyLzSzgiQisVPRokZvjFR4gjPHkWTWgkdUIiX3fjPLglKnM1Y2Y0XqASZHMGUCwDZtfVX0E0UY4TQVE1ZvjFRD0DZHU2LC8Dc3XzXqEjTZoFLogjdHIDR4E0UXoWUxHFNHIDSn4BZic1cVM1ZvjFRyQ0PLglKnEVcQcUVNUjUgsFLogTQIg2R4XWZgUWTWkkYpYTV3fjTMglK3IldEYzXvzzUOglKogjYXcEVxU0UYgCRRsDLtjFRlMSLgoWUrM0YvXUV3fDZQg1Mn8zMyDSX5UkQH8VTV8DZXkFRlwzQicVTWMVdvjFR1gjPHESQFEFLUY0SnomTMYGRBgDc3XzXqQCUXMWUV8DZXoGRncCZOcyLwDldUYDRuEkUOglXogjYLczXmE0UikGLogjcHIDRwTjQgASUV8DZ5IUS1gjPHQGNFM1ZzPEVyUkUOglXpgTcyLzSzgiQisVPRokZvjFRyfjPHkWTWgkdUIiX3fjPLglKnM1Y2Y0XqASZHMGUCwDZtfVX0E0UY4TQVE1ZvjFRG0DZHU2LC8Dc3XzXqEjTZoFLogDMHIDR4E0UXoWUxHFNHIDSn4BZic1cVM1ZvjFRyQ0PLglKnEVcQcUVNUjUgsFLogTPIg2R4XWZgUWTWkkYpYTV3fjTLYGRBgTdQcEV5UkLhgCRBwDZtf1XmcmUisFLogzbTMDSn4BZgUWTWkkSEYUXqASZHETSngTcyLzSzgiQisVPRokZvjFR2QTZHYFSGM1YQc0X4ASZHYGRBgTLEYTXvTkUOgldR0jcHIDRzgiQisFMTg0bUY0SngjZHU2LC8TctzlXq0zUYoGMC8jcIcUV4UkQiYFSGEVcQ01Tv.CaXsVRW8DZLkFR4XWZgUWTWkkYpYTV3fjPLglK3IldEYzXvzzUOglKogjYXcEVxU0UYgCRRsDLtjFRlMSLgoWUrM0YvXUV3fDdPg1Mn8zMyDSX5UkQH8VTV8DZDkFRlwzQicVTWMVdvjFR1gjPHESQFEFLUY0SnomTMYGRBgDc3XzXqQCUXMWUV8DZLoGRncCZOcyLwDldUYDRuEkUOgFRogjYLczXmE0UikGLogjcHIDRwTjQgASUV8DZ5IUS1gjPHQGNFM1ZzPEVyUkUOgFTpgTcyLzSzgiQisVPRokZvjFR4gjPHkWTWgkdUIiX3fjPLglKnM1Y2Y0XqASZHMGUCwDZtfVX0E0UY4TQVE1ZvjFRD0DZHU2LC8Dc3XzXqEjTZoFLogjdHIDR4E0UXoWUxHFNHIDSn4BZic1cVM1ZvjFRyQ0PLglKnEVcQcUVNUjUgsFLogTQIg2R4XWZgUWTWkkYpYTV3fjTMglK3IldEYzXvzzUOglKogjYXcEVxU0UYgCRRsDLtjFRlMSLgoWUrM0YvXUV3fDZQg1Mn8zMyDSX5UkQH8VTV8DZXkFRlwzQicVTWMVdvjFR1gjPHESQFEFLUY0SnomTMYGRBgDc3XzXqQCUXMWUV8DZXoGRncCZOcyLwDldUYDRuEkUOglXogjYLczXmE0UikGLogjcHIDRwTjQgASUV8DZ5IUS1gjPHQGNFM1ZzPEVyUkUOglXpgTcyLzSzgiQisVPRokZvjFRyfjPHkWTWgkdUIiX3fjPLglKnM1Y2Y0XqASZHMGUCwDZtfVX0E0UY4TQVE1ZvjFRG0DZHU2LC8Dc3XzXqEjTZoFLogDMHIDR4E0UXoWUxHFNHIDSn4BZic1cVM1ZvjFRyQ0PLglKnEVcQcUVNUjUgsFLogTPIg2R4XWZgUWTWkkYpYTV3fjTLYGRBgTdQcEV5UkLhgCRBwDZtf1XmcmUisFLogzbTMDSn4BZgUWTWkkSEYUXqASZHETSngTcyLzSzgiQisVPRokZvjFR2QTZHYFSGM1YQc0X4ASZHYGRBgTLEYTXvTkUOgldR0jcHIDRzgiQisFMTg0bUY0SngjZHU2LC8TctzlXq0zUYoGMC8jcIcUV4UkQiYFSGEVcQ01Tv.CaXsVRW8DZPkFR4XWZgUWTWkkYpYTV3fjPLglK3IldEYzXvzzUOglKogjYXcEVxU0UYgCRRsDLtjFRlMSLgoWUrM0YvXUV3fDdPg1Mn8zMyDSX5UkQH8VTV8DZDkFRlwzQicVTWMVdvjFR1gjPHESQFEFLUY0SnomTMYGRBgDc3XzXqQCUXMWUV8DZLoGRncCZOcyLwDldUYDRuEkUOgFRogjYLczXmE0UikGLogjcHIDRwTjQgASUV8DZ5IUS1gjPHQGNFM1ZzPEVyUkUOgFTpgTcyLzSzgiQisVPRokZvjFR4gjPHkWTWgkdUIiX3fjPLglKnM1Y2Y0XqASZHMGUCwDZtfVX0E0UY4TQVE1ZvjFRD0DZHU2LC8Dc3XzXqEjTZoFLogjdHIDR4E0UXoWUxHFNHIDSn4BZic1cVM1ZvjFRyQ0PLglKnEVcQcUVNUjUgsFLogTQIg2R4XWZgUWTWkkYpYTV3fjTMglK3IldEYzXvzzUOglKogjYXcEVxU0UYgCRRsDLtjFRlMSLgoWUrM0YvXUV3fDZQg1Mn8zMyDSX5UkQH8VTV8DZXkFRlwzQicVTWMVdvjFR1gjPHESQFEFLUY0SnomTMYGRBgDc3XzXqQCUXMWUV8DZXoGRncCZOcyLwDldUYDRuEkUOglXogjYLczXmE0UikGLogjcHIDRwTjQgASUV8DZ5IUS1gjPHQGNFM1ZzPEVyUkUOglXpgTcyLzSzgiQisVPRokZvjFRyfjPHkWTWgkdUIiX3fjPLglKnM1Y2Y0XqASZHMGUCwDZtfVX0E0UY4TQVE1ZvjFRG0DZHU2LC8Dc3XzXqEjTZoFLogDMHIDR4E0UXoWUxHFNHIDSn4BZic1cVM1ZvjFRyQ0PLglKnEVcQcUVNUjUgsFLogTPIg2R4XWZgUWTWkkYpYTV3fjTLYGRBgTdQcEV5UkLhgCRBwDZtf1XmcmUisFLogzbTMDSn4BZgUWTWkkSEYUXqASZHETSngTcyLzSzgiQisVPRokZvjFR2QTZHYFSGM1YQc0X4ASZHYGRBgTLEYTXvTkUOgldR0jcHIDRzgiQisFMTg0bUY0SngjZHU2LC8TctzlXq0zUYoGMC8jcIcUV4UkQiYFSGEVcQ01Tv.CaXsVRW8DZTkFR4XWZgUWTWkkYpYTV3fjPLglK3IldEYzXvzzUOglKogjYXcEVxU0UYgCRRsDLtjFRlMSLgoWUrM0YvXUV3fDdPg1Mn8zMyDSX5UkQH8VTV8DZDkFRlwzQicVTWMVdvjFR1gjPHESQFEFLUY0SnomTMYGRBgDc3XzXqQCUXMWUV8DZLoGRncCZOcyLwDldUYDRuEkUOgFRogjYLczXmE0UikGLogjcHIDRwTjQgASUV8DZ5IUS1gjPHQGNFM1ZzPEVyUkUOgFTpgTcyLzSzgiQisVPRokZvjFR4gjPHkWTWgkdUIiX3fjPLglKnM1Y2Y0XqASZHMGUCwDZtfVX0E0UY4TQVE1ZvjFRD0DZHU2LC8Dc3XzXqEjTZoFLogjdHIDR4E0UXoWUxHFNHIDSn4BZic1cVM1ZvjFRyQ0PLglKnEVcQcUVNUjUgsFLogTQIg2R4XWZgUWTWkkYpYTV3fjTMglK3IldEYzXvzzUOglKogjYXcEVxU0UYgCRRsDLtjFRlMSLgoWUrM0YvXUV3fDZQg1Mn8zMyDSX5UkQH8VTV8DZXkFRlwzQicVTWMVdvjFR1gjPHESQFEFLUY0SnomTMYGRBgDc3XzXqQCUXMWUV8DZXoGRncCZOcyLwDldUYDRuEkUOglXogjYLczXmE0UikGLogjcHIDRwTjQgASUV8DZ5IUS1gjPHQGNFM1ZzPEVyUkUOglXpgTcyLzSzgiQisVPRokZvjFRyfjPHkWTWgkdUIiX3fjPLglKnM1Y2Y0XqASZHMGUCwDZtfVX0E0UY4TQVE1ZvjFRG0DZHU2LC8Dc3XzXqEjTZoFLogDMHIDR4E0UXoWUxHFNHIDSn4BZic1cVM1ZvjFRyQ0PLglKnEVcQcUVNUjUgsFLogTPIg2R4XWZgUWTWkkYpYTV3fjTLYGRBgTdQcEV5UkLhgCRBwDZtf1XmcmUisFLogzbTMDSn4BZgUWTWkkSEYUXqASZHETSngTcyLzSzgiQisVPRokZvjFR2QTZHYFSGM1YQc0X4ASZHYGRBgTLEYTXvTkUOgldR0jcHIDRzgiQisFMTg0bUY0SngjZHU2LC8TctzlXq0zUYoGMC8jcIcUV4UkQiYFSGEVcQ01Tv.CaXsVRW8DZXkFR4XWZgUWTWkkYpYTV3fjPLglK3IldEYzXvzzUOglKogjYXcEVxU0UYgCRRsDLtjFRlMSLgoWUrM0YvXUV3fDdPg1Mn8zMyDSX5UkQH8VTV8DZDkFRlwzQicVTWMVdvjFR1gjPHESQFEFLUY0SnomTMYGRBgDc3XzXqQCUXMWUV8DZLoGRncCZOcyLwDldUYDRuEkUOgFRogjYLczXmE0UikGLogjcHIDRwTjQgASUV8DZ5IUS1gjPHQGNFM1ZzPEVyUkUOgFTpgTcyLzSzgiQisVPRokZvjFR4gjPHkWTWgkdUIiX3fjPLglKnM1Y2Y0XqASZHMGUCwDZtfVX0E0UY4TQVE1ZvjFRD0DZHU2LC8Dc3XzXqEjTZoFLogjdHIDR4E0UXoWUxHFNHIDSn4BZic1cVM1ZvjFRyQ0PLglKnEVcQcUVNUjUgsFLogTQIg2R4XWZgUWTWkkYpYTV3fjTMglK3IldEYzXvzzUOglKogjYXcEVxU0UYgCRRsDLtjFRlMSLgoWUrM0YvXUV3fDZQg1Mn8zMyDSX5UkQH8VTV8DZXkFRlwzQicVTWMVdvjFR1gjPHESQFEFLUY0SnomTMYGRBgDc3XzXqQCUXMWUV8DZXoGRncCZOcyLwDldUYDRuEkUOglXogjYLczXmE0UikGLogjcHIDRwTjQgASUV8DZ5IUS1gjPHQGNFM1ZzPEVyUkUOglXpgTcyLzSzgiQisVPRokZvjFRyfjPHkWTWgkdUIiX3fjPLglKnM1Y2Y0XqASZHMGUCwDZtfVX0E0UY4TQVE1ZvjFRG0DZHU2LC8Dc3XzXqEjTZoFLogDMHIDR4E0UXoWUxHFNHIDSn4BZic1cVM1ZvjFRyQ0PLglKnEVcQcUVNUjUgsFLogTPIg2R4XWZgUWTWkkYpYTV3fjTLYGRBgTdQcEV5UkLhgCRBwDZtf1XmcmUisFLogzbTMDSn4BZgUWTWkkSEYUXqASZHETSngTcyLzSzgiQisVPRokZvjFR2QTZHYFSGM1YQc0X4ASZHYGRBgTLEYTXvTkUOgldR0jcHIDRzgiQisFMTg0bUY0SngjZHU2LC8TctzlXq0zUYoGMC8jcIcUV4UkQiYFSGEVcQ01Tv.CaXsVRW8DZhkFR4XWZgUWTWkkYpYTV3fjPLglK3IldEYzXvzzUOglKogjYXcEVxU0UYgCRRsDLtjFRlMSLgoWUrM0YvXUV3fDdPg1Mn8zMyDSX5UkQH8VTV8DZDkFRlwzQicVTWMVdvjFR1gjPHESQFEFLUY0SnomTMYGRBgDc3XzXqQCUXMWUV8DZLoGRncCZOcyLwDldUYDRuEkUOgFRogjYLczXmE0UikGLogjcHIDRwTjQgASUV8DZ5IUS1gjPHQGNFM1ZzPEVyUkUOgFTpgTcyLzSzgiQisVPRokZvjFR4gjPHkWTWgkdUIiX3fjPLglKnM1Y2Y0XqASZHMGUCwDZtfVX0E0UY4TQVE1ZvjFRD0DZHU2LC8Dc3XzXqEjTZoFLogjdHIDR4E0UXoWUxHFNHIDSn4BZic1cVM1ZvjFRyQ0PLglKnEVcQcUVNUjUgsFLogTQIg2R4XWZgUWTWkkYpYTV3fjTMglK3IldEYzXvzzUOglKogjYXcEVxU0UYgCRRsDLtjFRlMSLgoWUrM0YvXUV3fDZQg1Mn8zMyDSX5UkQH8VTV8DZXkFRlwzQicVTWMVdvjFR1gjPHESQFEFLUY0SnomTMYGRBgDc3XzXqQCUXMWUV8DZXoGRncCZOcyLwDldUYDRuEkUOglXogjYLczXmE0UikGLogjcHIDRwTjQgASUV8DZ5IUS1gjPHQGNFM1ZzPEVyUkUOglXpgTcyLzSzgiQisVPRokZvjFRyfjPHkWTWgkdUIiX3fjPLglKnM1Y2Y0XqASZHMGUCwDZtfVX0E0UY4TQVE1ZvjFRG0DZHU2LC8Dc3XzXqEjTZoFLogDMHIDR4E0UXoWUxHFNHIDSn4BZic1cVM1ZvjFRyQ0PLglKnEVcQcUVNUjUgsFLogTPIg2R4XWZgUWTWkkYpYTV3fjTLYGRBgTdQcEV5UkLhgCRBwDZtf1XmcmUisFLogzbTMDSn4BZgUWTWkkSEYUXqASZHETSngTcyLzSzgiQisVPRokZvjFR2QTZHYFSGM1YQc0X4ASZHYGRBgTLEYTXvTkUOgldR0jcHIDRzgiQisFMTg0bUY0SngjZHU2LC8TctzlXq0zUYoGMC8TctzlXq0zUYoWSs8zM2HUXu0DahUWTWMFcqwVXsQyPOgGNwD1bMckVyU0QgcVTxDFdzLzS1UDahcFLwHVN1MDUAkTUP0TPRokZvjFR3gSLgMWUpE1YIYTXqEEaHYFVWgkbUcUV3fjTLQmKogTcyLzS04xUXgWQVEVdzLzSRgSLgMWSWM0YzXEVsUEahkicoQUc3XUX4QyPOIENwD1bAIkVpASZHkWTWMlZqESXAgyZhUGNVEFZtfVXmAiUYgCR3QkdUcTVugSLWETRBgDLMcUV3ASZHYGRBgzZQYkV5UDaXIWUV8DZDkFRlQTLXo2ZrM1ZvjFR2gDZOciKUgEdEYUXqE0UYgWSs8zMtTEV3UjUgsVTWkEdAIjXmkzUXMWUFM1ZIckTpASZHgGNwD1bMUkV0TULhglKnM1Y2Y0XqASZHAyLBwDZ2f1S23RUXgWQVE1ZQcUV3EjPhcVRWg0bUYzXqkzURoFLogDd3DSXyUjZXkGNrIlcQckV0QiUScVTWkEdqYEVx0TaHYFVWgkbUcUV3fjTLQmKogTcyLzSPUDahcFLVkkdUwlXl4xUXgWQVE1ZQcUV3sFQYgCRnIVc3XUXLsVLhoWUrE1ZIcDU00zUZo2ZwDFcIIDRwTjQgASUV8DZTk1R1gDdKkicCQ0YIcEVyUkQisVRGgjcEwlXmAiUYoWUrIVRQY0SngjLgUGLwPUcU0lXoUkQQs1cVgEMvnWXpUEaHYFVWgkbUcUV3fjPLQmKogTcyLzSPUDahcFLVkkdUwlXl4xUXgWQVE1ZQcUV3sFQYgCRnIVc3XUXMgiQYAycVgkdqESXzgiZg8TVrkEZtf1XmcmUisFLogzcyHDSncCZOciKUgEdEYUXqE0UYgWPBI1YIcEVyUkQisVRWIkZvjFR3gSLgMWTToUdQcEVz0jUYITUFMlLUYUVzACUZkVSsgjYXcEVxU0UYgCRRwjLyHDSncCZOciKUgEdEYUXqE0UYgWPBI1YIcEVyUkQisVRWIkZvjFR3gSLgMWQTEFZqYUVz0jUYEDLwDFLzXzXn4BZic1cVM1ZvjFRywTZKYGR3sTN1k2RPUDahcFLVkkdUwlX4QyPOUGRvDVcvv1S2fDLgUGLFgzaQY0SnwzQiASTVoUcIo2U3gSLgMWRBgDcEYUXqASZHMUTWMlZqESXkkjZHYFUxH1ZIc0Sn4RZHYFUFk0aQcEVncmUYgCRRwDZtHEVoE0UZESUV8DZtjFR4X2PTcVRWg0bUYzXqkjLhkicCQ0YIcEVyUkQisVRGgjcEwlXmAiUYoWUrIVRQY0SngjLgUGLwP0aucUV4kjPHESQFEFLUY0SngUZKYGR3sTN1MDUmkzUXMWUFM1ZIcDR1UDahcFLVkkdUwlXIEkUOgFRxDVcvXETn0jLggWPGM1a3vVXMUjQisVRWo0Y2EiXn4BZic1cVM1ZvjFR2MiPLg1Mn8zMtTEV3UjUgsVTWkEdAIjXmkzUXMWUFM1ZIckTpASZHgGNwD1b2QkV4E0UYQWUrIFT3DiXuE0UZUGMrgjYXcEVxU0UYgCR3wDcTMkSzn1TNQiZCwjdXkGS3QUZMMCR3sTN1MDUmkzUXMWUFM1ZIcDR1UDahcFLVkkdUwlXIEkUOgFRxDVcvDCU0UUahkVUFE0Z2YEVz.idgoVUrgjYXcEVxU0UYgCRBwDctjFR0MyPOAUQrI1YvXUV5UEahYlKWgEdEYUXqE0UYg2ZDkENHglX0giUg0DNFkEL2YEV5sVLgQGNpE1SYwVVn4BZic1cVM1ZvjFR2MiPLg1Mn8zMtTEV3UjUgsVTWkEdAIjXmkzUXMWUFM1ZIckTpASZHgGNwD1bQQkV4E0UXQWSVkkPUYzXxTkUYQGLToUZM0FRlg0UXIWUWkENHIESxLiPLg1Mn8zMtTEV3UjUgsVTWkEdAIjXmkzUXMWUFM1ZIckTpASZHgGNwD1bEQUXnslUYQWSVkUPvDSXvPiQiglKnM1Y2Y0XqASZHMGSosjcHg2R4XWdKAUQrI1YvXUV5UEahkGMC8TcHASX0ACaOcCRvDVcvXDRuEkUOgFSGMFLQYkV00jdWgGNwD1bIIDRzUjUgsFLogzTQc0XpsVLgUVSpgjYTIiXqkzUOglKogjYTYTVuE0UXg1cVkENHIESn4hTXkVTWoULUY0Sn4RZHkicCQ0YIcEVyUkQisVRxHVN1MDUmkzUXMWUFM1ZIcDR1UDahcFLVkkdUwlXIEkUOgFRxDVcvDCUu81UYkWRBgTLEYTXvTkUOglXosjcHg2R4X2PTcVRWg0bUYzXqkzQHYWQrI1YvXUV5UEahkTTV8DZHISX0AiUPgVSxDFdAczXugCag0TQFM1ZIckVmcWLhglKnM1Y2Y0XqASZHg2LBwDZ2f1S23RUXgWQVE1ZQcUV3EjPhcVRWg0bUYzXqkzURoFLogDd3DSXycGUZkWTWkEcUwlXPgSLh8VTWoUczvFRlg0UXIWUWkENHgWSz4RZHU2LC8DTEwlXmAiUYoWUrIlYtbEV3UjUgsVTWkEdqQTV3fDZhUGNVE1T3X0X30jUYQTUFE1Yqc0T0EkUYglKnM1Y2Y0XqASZHY2LBwDZ2f1S23RUXgWQVE1ZQcUV3EjPhcVRWg0bUYzXqkzURoFLogDd3DSXyAidgoVUGE1YQckV0QSLSQGNpkEaIIDRwTjQgASUV8DZDk1R1gDdKkicCQ0YIcEVyUkQisVRGgjcEwlXmAiUYoWUrIVRQY0SngjLgUGLFE0aMczXmQSLXsVRTkkdicUVqQiUS8VSwHFZtf1XmcmUisFLogzchk1R1gDdKkicCQ0YIcEVyUkQisVRGgjcEwlXmAiUYoWUrIVRQY0SngjLgUGLVA0bIYkVqQSLXsVQTEVcU0VX5kjPHESQFEFLUY0SnoGdLQmKogTcyLzS04RUXgWQVE1ZQcUV30TaOcyMnQUc3XUX4XWZTUGNVElYpYTV3fDdXIGNwH1ZvPkVogyZhUGNVEFZtfVXmAiUYgCR3Akb3DiXqgSUS8VSwbkT3DSXykjPHASSWkEdvjFR1gjPHsVTVokdEwFVxUkUOglKogjYDECV5sFaisFLogjcHg1S23RUXgWQVE1ZQcUV30TaOciKUgEdEYUXqE0UYgWPBI1YIcEVyUkQisVRWIkZvjFR3gSLgMWSUoUMUEiXn4BZic1cVM1ZvjFR4MiPLg1Mn8zMtTEV3UjUgsVTWkEdAIjXmkzUXMWUFM1ZIckTpASZHgGNwD1bEoFV4gCahYWTWoUczX0TmE0UYg2ZVgkbM0FRlg0UXIWUWkENHIDSz4RZHU2LC8DTEwlXmAiUYoWUrIlYtbEV3UjUgsVTWkEdqQTV3fDZhUGNVEFSqEiX5UEagsVRGQUcMckV5sVLgQWRBgTLEYTXvTkUOgFSosjcHg2R4X2PTcVRWg0bUYzXqkzQHYWQrI1YvXUV5UEahkTTV8DZHISX0ASLTUWUsIVZUYTTqcmUXQCL5ElZUwFRlg0UXIWUWkENHIDSz4RZHU2LC8DTEwlXmAiUYoWUrIlYtbEV3UjUgsVTWkEdqQTV3fDZhUGNVEVS3XTVvbmUXo2ZwDFc3nVXOkEaYglKnM1Y2Y0XqASZHY2LBwDZ2f1S23RUXgWQVE1ZQcUV3EjPhcVRWg0bUYzXqkzURoFLogDd3DSXyEEUZkWTWgEcMYUVBUkQiISUVkEcvPkVo0TaHYFVWgkbUcUV3fjTLIyLBwDZ2f1S23RUXgWQVE1ZQcUV3EjPhcVRWg0bUYzXqkzURoFLogDd3DSXyUDUgg1ZVkEcMYUVAASLgACMFMFZtf1XmcmUisFLogzbpk1R1gDdKkic4sDTEwlXmAiUYoWUrIVdzLzS0gDLgUGLr8zM2fFU0giUgkGMC8TcHASX0ASLh0TQrE1YiYUV3QyPOUGRxDVcvDiXuAiUiIWQFMVcI01S23hLgk2ZFM1a3vVXuQSLYkicCI1YIcEVy0TaOciKUAkTEQ0TlolQYgCRnIVc3XUXSgiUigWSVkUPzDSVxUEaHYFVWgkbUcUV3fjTNY2LBwDZ2f1S23RUPIUQTMkYpYTV3fDZhUGNVE1T3X0X30jUYQzZwHldEwVXoUEaHYFVWgkbUcUV3fDdLQmKogTcyLzS04xUXgWQVEVdzLzS04hLgk2ZFM1a3vVXuQSLYkic4sjcIISXskzUXMGMC8Td3X0X30jUY8FMrkUcAIUXmQiUiwVQwfkdU0lXqkzUOgFQTMlZqESXkAidgoVUFE1azDSVn4hTgc1ZrEFUUYDY5ASZHMTUFElb3vFRlAkLgYWTUk0LQc0SnY1ULglKngUcQczX0AiQUs1YGMFNHIkTN0TQUIEMRwDZtfGV0cWLgASRW8DZXwVVq0jUXoVRogEZtfGV0AiQhUGMVkEcQICUu81UYgCRBwDZtfmXq0jQi8FNrEVS3XTVqASZHYGR3sTN1k2R4M1UXMGMC4hKt3hKt3hKt3hKlIUUMQUTPkzUZESQFM1ZQQEV5UjQtDDQlAEMAcEV40zQtDDQ14hK5EjKt3hKt3hKt3hRUACTEEzZh8VVWgkdUYTTmE0UXwyKIMzasA2atUlaz4COuX0TTMCTrU2Yo41TzEFck4C."
                        },
                        "snapshotlist": {
                            "current_snapshot": 0,
                            "entries": [
                                {
                                    "filetype": "C74Snapshot",
                                    "version": 2,
                                    "minorversion": 0,
                                    "name": "SWAM Cello 3",
                                    "origin": "SWAM Cello 3.vst3info",
                                    "type": "VST3",
                                    "subtype": "Instrument",
                                    "embed": 0,
                                    "snapshot": {
                                        "pluginname": "SWAM Cello 3.vst3info",
                                        "plugindisplayname": "SWAM Cello 3",
                                        "pluginsavedname": "",
                                        "pluginsaveduniqueid": -298341311,
                                        "version": 1,
                                        "isbank": 0,
                                        "isbase64": 1,
                                        "blob": "22722.VMjLgjKV...O+fWarAhckI2bo8la8HRLt.iHfTlai8FYo41Y8HRUTYTK3HxO9.BOVMEUy.Ea0cVZtMEcgQWY9vSRC8Vav8lak4Fc9DiM4TiMtXUSGM1UA4hKtXlKt3hKP4hKt3hKtvjdXQ2bD4hKHQTRFkjdP4VPt3hKHYGUoUULL4BStLjKt3hKtPjKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3hKt3RP24VUCkzTHcTQD4hK1k2Sy.iQgYFVWkEdMckV0QiUOgFQosjcHIDRqQSLXUWTVoEciY0SnQUQUYDLB4DZ2j1SlYWdhISQVElYPcEY1UkUOgFSEMFdqwVXs0TaHYFVWkEdMckV0QiUOgFQCwDZtflXmQSLYsFLogTdXMzRynVZHYFTWgUaMc0SnQjdXUWUxHldqECVn4BdhUWVFMlLEwlXqkUUYgWSWoUczX0SnwTZKcGRosjcHIDR4sVagk1c5EVZyY0SnQTZHkicCk0YQcUV5slUgsVPnM1Y2Y0XqASZH0DNrElY5QEVzDjPHomKnwzctMUSz31PLcmKnwjcHkVSrwjTLYmbogTcyLzS1kjLg0VRWg0bAgVXmAiUYgCRBQ1ZzXEVwUUaXsFNUE1YqwVXnMyPOYGNwH1aQckV0QiQHkVSFwjc5kFRyQTZHYFSwfUdHM0SnomTLglKBIVZvjFRyQTZHU2LC8jb3DCVw0zQHkGNVMFcQYUVzMlUZQWUV8DZtjFRlomUZo1ZVE1YAcjXuQSLYgCRBwDZtHUXu0DahUWTWMFcqwVXsASZHYGRBgDd3DSXy0zUZMWUGE1YQISX3ASZHYGR3sTN1kmX0UUagoVUrEVaqwVXqQyPOYWQrI1YvDiX4X2PTETRUAUSAIkVpASZHUTQUkEcEwFVxUkQYglKnM1Y2Y0XqASZHY2LBwDZ2f1S23RUPIUQTMkYpYTV3fjTQE0YVoUamESTmsFagglKnM1Y2Y0XqASZHY2LBwDZ2f1S23RUPIUQTMkYpYTV3fjTQE0cwDlLiQEVuQCaHYFVWgkbUcUV3fjPLQmKogTcyLzSPUjZTEDLDgzaQY0SnQEUTM2ZFkkQIcUV2kjPHESQFEFLUY0SnI1TMY2LR0DZ2f1S23RUPIUQTMkYpYTV3fjTQEELVokZiQEVuQCaHYFVWgkbUcUV3fjPLQmKogTcyLzSPUjZTEDLDgzaQY0SnoGUXQWUWgkbQslXqASLgIGNVMUcQYUVn4BZic1cVM1ZvjFR1MiPLg1Mn8zMtTETRUDUSYlZFkENHIDUu8VajQENrE1ZIIDRwTjQgASUV8DZtj1Ryn1TNQiZS4DMhkVS2Q0PNcGTowzcHg2R4X2PTETRUAUSAIkVpASZHcVSwf0TQcEYxUEaHYFVWgkbUcUV3fjPLQmKogTcyLzSPUjZTEDLDgzaQY0SnQjQgoWVToEciYDUmkzUXMWRBgTLEYTXvTkUOglKosjcHg2R4X2PTETRUAUSAIkVpASZHcVTxnkTEYUX1EUUZMWUrgjYXcEVxU0UYgCRB0DctjFR0MyPOAUQpQUPvPDRuEkUOgFQVMld3XTTqE0UYkVTWoUczXTUuAiUYglKnM1Y2Y0XqASZHcGRosjcHg2R4X2PTETRUAUSAIkVpASZHgFNwLlQ3vlXoUkQTcVRWg0bIIDRwTjQgASUV8DZtj1R4QzPLYmKCwjctjFS4Y1PMcmYS0zLHg2R4X2PTETRUAUSAIkVpASZHgFNwLFSqwVV5ETUXgWQVEFZtf1XmcmUisFLogjcyHDSncCZOciKUAkTEQ0TlolQYgCRngUci01T0sVLhsVPUgEdEYUXn4BZic1cVM1ZvjFR1MiTMg1Mn8zMtTETRUDUSYlZFkENHgFV0M1QTUWSWokdqESXzETUXgWQVEFZtf1XmcmUisFLogjcyHES5o1PLYmKCwjcLMkS4wzTNYGVo0DZ2f1S23RUPIUQTMkYpYTV3fDZXU2XsQ0YzXTV0AiQTUWSGQ0YIcEVykjPHESQFEFLUY0SnQTZKYGR3sTN1MDUAkTUP0TPRokZvjFRngSLiMUTWgEdQcDUmkzUXMWRBgTLEYTXvTkUOglKosjcHg2R4X2PTETRUAUSAIkVpASZHgFNwL1azDSVSUEagkWRBgTLEYTXvTkUOglKosDLHg2R4X2PTETRUAUSAIkVpASZHoVRFEFR3XTXp0TQigWSUkkbUECV5sVLgQWRBgTLEYTXvTkUOgFQosjcHg2R4X2PTETRUAUSAIkVpASZHo1ZsE1YvXkVoE0ZhcFMwH1aQckV0QSLhglKnM1Y2Y0XqASZHc2LBwDZ2f1S23RUPIUQTMkYpYTV3fjTYcVRGEFMIUUVrcmUYkVTWoUczDSTmsFagglKnM1Y2Y0XqASZHY2LR0DZ2f1S23RUPIUQTMkYpYTV3fjTYMSPsI1ZMIiXugCagglKnM1Y2Y0XqASZHY2LBwDdPMDS14xPLYmKowjclkVS2gUZLECR3sTN1MDUAkTUP0TPRokZvjFRsUULhoWUsI1ZvnWXpUkQTcVRWg0bIIDRwTjQgASUV8DZDk1R1gDdKkicCQUPIUETMEjTZoFLogjaEwlXygCag8VSwD0YqwVXAkjPHESQFEFLUY0Sn4RZKYGR3sTN1MDUAkTUP0TPRokZvjFRtUDahMGNrE1aMESTmsFagITRBgTLEYTXvTkUOglKosjcHg2R4X2PTETRUAUSAIkVpASZH4VQrI1b3vVXu0TLTs1cVkUZQcETn4BZic1cVM1ZvjFR3MiPLg1Mn8zMtTETRUDUSYlZFkENHIjVmkzUgUGMVoUZMUUVxUULXoWRpgjYXcEVxU0UYgCR3wDctjFR0MyPOAUQpQUPvPDRuEkUOglYVgEdvDSXzsVLXkWS5EFcQ0lX0cGaHYFVWgkbUcUV3fjPMQmKogTcyLzSPUjZTEDLDgzaQY0SnYlUXgGLwDFcqECV4UkZgcVRFE1ZQwFRlg0UXIWUWkENHIDSz4RZHU2LC8DTEoFUAACQH8VTV8DZlYEV3ASLgQ2ZwfUdAUEV3UjUgglKnM1Y2Y0XqASZHY2LBwDZ2f1S23RUPIUQTMkYpYTV3fjTZQWTWkEdEECV5sFaisVR5ElLqwVXskjPHESQFEFLUY0Sn4RZKQiKCwjctLDS1wzTMICVowjLlkVSzfDdKkicCQUPIUETMEjTZoFLogzaIICUqcmUYkVTWkkZIIDRwTjQgASUV8DZtj1R1gDdKkicCQUPIUETMEjTZoFLogTbUYUV1kjdgISTToEdUECV5sVLgQWRBgTLEYTXvTkUOglKosjcHg2R4X2PTETRUAUSAIkVpASZHIWUwj0YQISXSM1UXYWRBgTLEYTXvTkUOgFQosjcHg2R4X2PTETRUAUSAIkVpASZHMWQVoEcYASXxU0UgsVRBgTLEYTXvTkUOgld3wDctjFR0MyPOAUQpQUPvPDRuEkUOgldVgEcUcEVxkjdgIyZrEVaIIDRwTjQgASUV8DZtj1R1gDdKkicCQUPIUETMEjTZoFLogzbEwVXvTjQgIDNwL1azDSVSUkLhoWQVoEcznWX5UEaHYFVWgkbUcUV3fjTLQmKogTcyLzSPUjZTEDLDgzaQY0SnomUXkWTWkEdQU0XzUEaHYFVWgkbUcUV3fjPMomKosjcHg2R4X2PTETRUAUSAIkVpASZHMWQwHldUwlXVgiQgACLVkETIISXoUULhk2ZrEVaIIDRwTjQgASUV8DZtj1R1gDdKkicCQUPIUETMEjTZoFLogTcAcUVz0TQig2ZrEVaM0FRlg0UXIWUWkENHIDSzQUZHU2LC8DTEoFUAACQH8VTV8DZtbEVzEDLgoWRBgTLEYTXvTkUOglKosjcHg2R4X2PTETRUAUSAIkVpASZHYWQrElc3XzXTs1QhsVRBgTLEYTXvTkUOgFRosjcHg2R4X2PTETRUAUSAIkVpASZHY2ZFMVZmwFTqQiQYglKnM1Y2Y0XqASZHY2LBwDZ2f1S23RUPIUQTMkYpYTV3fjPh81asQVS3XTVxkjPHESQFEFLUY0Sn4RZKMiKCwjctLDS1I1TLACRS0DLhkGSxfDdKkicCQUPIUETMEjTZoFLogjcqwFY0rVLXcVTxDFT3XTXzjjPHESQFEFLUY0SnQTZKYGR3sTN1MDUAkTUP0TPRokZvjFR1cmUXQCL5ElZUYDUmkzUXMWRBgTLEYTXvTkUOglKosjcHg2R4X2PTETRUAUSAIkVpASZHYGNFEFMAcjV0QiUjAUQrI1YvvFRlg0UXIWUWkENHgGSz4RZHU2LC8DTEoFUAACQH8VTV8DZtHSX3E0UXMWUrEld3XTUuAiUYglKnM1Y2Y0XqASZHc2LBwDZ2f1S23RUPIUQTMkYpYTV3fDZhcFMFkUcvvVTuQSLYsVRsgjYXcEVxU0UYgCRBwDcTkFR0MyPOAUQpQUPvPDRuEkUOgFRWk0Y2Y0T0QSLg8TPGMFZtf1XmcmUisFLogTdyHDSncCZOciKUAkTEQ0TlolQYgCRnI1ZYcUV3kjUS81YsgjYXcEVxU0UYgCRRwzLyHDSncCZOciKUAkTEQ0TlolQYgCRnI1ZYcUV3kjQU8FLVkEZtf1XmcmUisFLogjcyHUSncCZOciKUAkTEQ0TlolQYgCR3IVcIcTVuQSLgAUQrI1YvvFRlg0UXIWUWkENHIDSz4RZHU2LC8DTEoFUAACQH8VTV8DZLczXm0TLXcVTxDVRzXzXqkTaic1cFU0avXUVn4BZic1cVM1ZvjFR2MiPLg1Mn8zMtTETRUDUSYlZFkENHgmX5sVLXE2ZrE1ZMIiXPUDahcFLrgjYXcEVxU0UYgCRBwDcTkFR0MyPOAUQpQUPvPDRuEkUOgFSGMFdqwVXsEzPiACMVkEZtf1XmcmUisFLogTdXk1R1gDdKkicCQUPIUETMEjTZoFLogTdQ0lXuQSLYIUUwHFZtf1XmcmUisFLogjcyHUSncCZOciKUAkTEQ0TlolQYgCR3IldIckVzMVLhkDMFM1ZI01XmcmULglKnM1Y2Y0XqASZHIyLBwDZ2f1S23RUPIUQTMkYpYTV3fDdhoWRWoEciEiXIQiQisVRsM1Y2wFSn4BZic1cVM1ZvjFRxLiPLg1Mn8zMtTETRUDUSYlZFkENHgmX5kzUZQ2XwHVRzXzXqkTaic1cwvDZtf1XmcmUisFLogjLyHDSncCZOciKUAkTEQ0TlolQYgCR3IldIckVzMVLh0DNFk0Z2wFRlg0UXIWUWkENHIDSz4RZHU2LC8DTEoFUAACQH8VTV8DZP0lXqASLgIGNVMUcQYUVn4BZic1cVM1ZvjFR1MiPLg1Mn8zMtTETRUDUSYlZFkENHIzX3UkUgU2cwDFTEwlXmACaHYFVWgkbUcUV3fjPLQmKogTcyLzSPUjZTEDLDgzaQY0SnAUahsFLwDlb3DCU1UkUYoVRBgTLEYTXvTkUOgFUosDMtLDS14xPLYmZS0TdXkWS5wTZLg1Mn8zMtTETRUDUSYlZFkENHg1XqcWLgk1ZFMFMIIDRwTjQgASUV8DZDMjSz4RZHU2LC8DTEoFUAACQH8VTV8DZXckVnkzUXoGNFE0ZAczXtkjPHESQFEFLUY0Sn4RZKoGUS4DMpMkSzH1PNACTowTdHkWSzfDdKkicCQUPIUETMEjTZoFLogTLqwFV3UjQiUWVTgkZUYkTzkjPHESQFEFLUY0SngzTMY2LBwDZ2f1S23RUPIUQTMkYpYTV3fDZi8VRrI1YQISXRUjQisVRBgTLEYTXvTkUOgFToszLlMkSzn1TNMCVo0jdlMUSvnVZMg1Mn8zMtTETRUDUSYlZFkENHg1XukDahcVTxDlTEYzXqkTUXQWTrgjYXcEVxU0UYgCRRwTLyHDSncCZOcyMBI1YIcEVy0TaOcyM3IVcU0VXpUEag01ZrE1ZzLzSyslQY8FLVgkcAckVzMFaOciKWgEdEYUX4QyPOAUQpQUPvPDRuEkUOglb5Q0bqYTVu0DQRglKnM1Y2Y0XqASZHg2LBwDZ2f1S23RUPIUQTMkYpYTV3fjTSETQUAUSYQEVoEkLgg2ZWM0YAcjXuQSLYglKnM1Y2Y0XqASZHY2LBwDZ2f1S23RUPIUQTMkYpYTV3fjTSETQUAUSQslXmQSLhYGNwH1ZIIDRwTjQgASUV8DZtj1R1gDdKkicCQUPIUETMEjTZoFLogzYQczXm0TLZQ0ZGI1ZIIDRwTjQgASUV8DZLk1R1gDdKkicCQUPIUETMEjTZoFLogDZMYjTukTUYkWTEoEdUEiXtgiQgoVRBgTLEYTXvTkUOglKosjdpMkSzn1TNQiXCwzcpkWSwHVdMECR3sTN1MDUAkTUP0TPRokZvjFRnkzUYcVTGo0P3vVX5kjLgI2cVkEdEQzXw0TUYQWSsgjYXcEVxU0UYgCRnwDctjFR0MyPOAUQpQUPvPDRuEkUOgFRrI1ZEYzXt0jdgQWTsIVc2YTXqkzUSUWTVkEZtf1XmcmUisFLogjcyHDSncCZOciKUAkTEQ0TlolQYgCR3g0YYckV50DLXc1cVkEZtf1XmcmUisFLogzcyHDSncCZOciKUAkTEQ0TlolQYgCRRk0LA0lXSEUahIUUwHFTEwlXmACaHYFVWgkbUcUV3fjTLQmKogTcyLzSPUjZTEDLDgzaQY0SnImUYQSSvL1aQICVtUULh8TSFM1YYcUVTkzUXQWSGIFZtf1XmcmUisFLogjcyHDSncCZOciKUAkTEQ0TlolQYgCR3o0ZqICUxrlQik1YVkUdAUEVsUULTIyZFMVZmwFRlg0UXIWUWkENHIDSz4RZHU2LC8DTEoFUAACQH8VTV8DZxEiXVUkQgIUUVE1YA0FRlg0UXIWUWkENHIDSzQUZHU2LC8DTEoFUAACQH8VTV8DZ5YkVokjLgQUUsE1ZyQUVzzDLi8VTxfkaUEiXRUULhsVTsgjYXcEVxU0UYgCRRwDctjFR0MyPOAUQpQUPvPDRuEkUOgldVoUZIISXTUUags1cTk0YI0VXBslLRs1ZxPkLqYzXoclUYkWRBgTLEYTXvTkUOglKosjcHg2R4X2PTETRUAUSAIkVpASZHM2ZFk0aAslX0kkUZIWUrgjYXcEVxU0UYgCRRwDctjFR0MyPOAUQpQUPvPDRuEkUOg1LwDldUEyTrkEaUs1cwDVZqYzXzjjPHESQFEFLUY0SnQTZKYGR3sTN1MDUAkTUP0TPRokZvjFR1UDag8VSrgjYXcEVxU0UYgCRBwDctjFR0MyPOAUQpQUPvPDRuEkUOglKWokdMYjVBUEagoVT5ElLzvFRlg0UXIWUWkENHgFS5MiPLg1Mn8zMtTETRUDUSYlZFkENHIjXuEkLX4VRTkEcQYUU1kjPHESQFEFLUY0SngzPMQmKogTcyLzSPUjZTEDLDgzaQY0Sn4xUZUyax.Uc2YzTqMFagUWS5EFcQ0lX0cGaHYFVWgkbUcUV3fjPLQmKogTcyLzSPUjZTEDLDgzaQY0Sn4hLggWTWg0bMUjXxslQiIUQFM1a3XDUmkzUXMWRBgTLEYTXvTkUOgFUCwDctjFR0MyPOAUQpQUPvPDRuEkUOglKxDFdQcEVyUEagoGNw.kdIcTXn4BZic1cVM1ZvjFR1MiPLg1Mn8zMtTETRUDUSYlZFkENHIjX0kzQicFLVkEcQISXMUjQjQ0ZVE1ZIIDRwTjQgASUV8DZPk1R1gDdKkicCQUPIUETMEjTZoFLogDdUECVqsFaisFLTIEQqoGTtUDagQWUFEFZtf1XmcmUisFLogzchk1R1gDdKkicCQUPIUETMEjTZoFLogDdUYTXqUTLhs1XUoEcQECT0QiQigGNFElbUwlXMgiQYsVRBgTLEYTXvTkUOglKosjcHg2R4X2PTETRUAUSAIkVpASZHkWUxHldEYkVzkjPHESQFEFLUY0Sn4RZKYGR3sTN1MDUAkTUP0TPRokZvjFR4UkLhoWQVoEcIUEVyETaHYFVWgkbUcUV3fjPLQmKogTcyLzSPUjZTEDLDgzaQY0SnAUahcFMwHlc3DiXqkjPHESQFEFLUY0Sn4RZKYGR3sTN1k2R1UDahcFLwHVN1M0TIEEURIUUVE1YAcjXuQSLYQUQrgkbUw1S2nGURQzZpQ0ZvXEV1EzUZQ2XVEEcQ0lXzDjTYQWQrgkbUYTV3fjTLglKBI1YIcEVyUkQisVRWIkZvjFRqc1QhgWUwHVdqESXzkjPHk1YVgEczXUVxASZHcmXogjY5YUV40zUX0VUFUEMAcUV3fjTLglKREVdIY0SnQzTLglKBEVdIY0SnomTLg1LC8TSqQTTIkTUYMWQFIlcqwVXs0DUigWVWkkYpwVX1U0QiUFLVoEcvjFR1MiPLglKRoEcAc0X5gSUgc1YW8DZDkFSxLiPLglK3EFLQIyUysFaggCR3wDctjFRlciUioGNUE1Ymc0SnQTZLAyLBwDZtfmXtUjQhsFLogjcyHDS4o1TNQiZS4DMpMES1Q0TNkmK4wTdHIDR4s1UgMWUFMFdqc0Sn4RZKMiKCwjctLDS1QzTLQCRCwDMHMkSn4BZXQSPWgUdMc0Sn4RZHYFRVokc3XTXmkzUOglKogTcyLzS0oGURQzZpQ0ZvXEV1EzUZQ2XVEEcQ0lXzPyPO0zZDEURIUUVyUjQhY2ZrEVaUoVX5kzUjYFUrE1YIYTXqEkUOgFQogjYtbEV3UjUgsVTWkEdqQTV3fDZi8VRrI1YQISXDUkQho2YrgjYLYjVmQCags1cV8DZDkWSn4hTgsVSxH1YiYUVTs1QhsFLogzcHIDRy0TaXgCRRwDZtHTX4kjUOgldRwDZyLzSMsFQQkTRUk0bEYjX1sFag0VSTMFdYcUVloFagYWUGMVYvXkVzASZHY2LBwDZtHkVzEzUioGNUE1Ymc0SnQTZLIyLBwDZtfWXvDkLWM2ZrEFNHIESz4RZHY1MVMld3TUXmc1UOgFQSwjcyHDSn4Bdh4VQFI1ZvjFR1MiPLglK3IFMvXUXqEUahQCLogjcyHUSn4BZXQSPWgUdMc0Sn4RZHYFRVokc3XTXmkzUOglKogTcyLzS0oGURQzZpQ0ZvXEV1EzUZQ2XVEEcQ0lXzPyPO0zZDEURIUUVyUjQhY2ZrEVaUoVX5kzUjYFUrE1YIYTXqEkUOgFQogjYtbEV3UjUgsVTWkEdqQTV3fDZi8VRrI1YQISXRUjQisVRBgTZmYEVzQiUYIGLogzchkFRlomUYkWSWgUaUYTUzDzUYgCRRwDZtHUX4kjUOgFQS4DZtHTX4kjUOgldRwDZyLzSMsFQQkTRUk0bEYjX1sFag0VSTMFdYcUVloFagYWUGMVYvXkVzASZHY2LBwDZtHkVzEzUioGNUE1Ymc0SnQTZLIyLBwDZtfWXvDkLWM2ZrEFNHIDSz4RZHY1MVMld3TUXmc1UOgFQowjLyHDSn4Bdh4VQFI1ZvjFR1MiPLglK3IFMvXUXqEUahQCLogjcyHUSn4BZXQSPWgUdMc0Sn4RZHYFRVokc3XTXmkzUOglKogTcyLzS0oGURQzZpQ0ZvXEV1EzUZQ2XVEEcQ0lXzPyPO0zZDEURIUUVyUjQhY2ZrEVaUoVX5kzUjYFUrE1YIYTXqEkUOgFQogjYtbEV3UjUgsVTWkEdqQTV3fDZXU2XsEUcIICVqETUXgWQVEFZtfGVtUDagQWUFEFNHIESxfjPHMWUwHVdEESVqEUUjYWUV8DZDkFRloWLhgFLogzchkFRlYWLhgFLogzbDkFR4X2TSkTTTIkTUYUXmEzQh8FMwj0PU0lXwTkQH8FMFIFLQIyUysFaggCRBwDctjFRloFagYWUGMVYvXEVy.SZHcGR40DctjFRlciUioGNUE1azX0Sn4RZKYGRBgTcUczXkAiUXMCLogzcHkWSz4RZHYFSGo0YAcUV3fjPLQmKogjYLcEYyAiUYoWRWQFNHIDSzQUZHYFRVQlcEEiX4ASZHYGRBgDZqYjX0cmUXgGLogjcHg2R4XWdK0zZDEURIUUVyUjQhY2ZrEVaUoVX5kzUjkicSMURQQkTRUkUgcVPGI1azDSVEQiQig2ZGgzZzXEVncmUYoFLogzcHIDR1UDahcFLVkkdUwlXIEkUOgFRwDlLAASX4slQi8FNrEFTEwlXmACaHYFSFo0YzvVXqcmUOgFQ40DZtHUXq0jLhc1XVkEUqcjXqASZHcGRBgzbM0FV3fjTLECRBgjbM0FV3fjTKcGRn8zM5QkTDslZTsFLVgkcAckVzMVLPASRsM1ZAIkVzEzUioGNUE1azX0Sn4RZKYGRBgzazXjXvDkLWMWQFQFNHIES3IVZKYGRBgTcUczXkAiUZQGLogjcyHDSn4BdgASTxb0bEYDY3fjTLgmXosjcHIDR4clUXYWUV8DZtj1R1gjPHk2ZWE1bUYzX3s1UOglKosDLHIDRns1QhcVSxHFNHIDSn4BZX8VPxDlbEwlX3fjPLg1Mn8zM2H0TIEEURIUUVE1YAcjXuQSLYUDMFMFdq01S2nGURQzZpQ0ZvXEV1EzUZQ2XVEEcQ0lXzDjTYQWQrgkbUYTV3fjTLglKBI1YIcEVyUkQisVRWIkZvjFR5kzUYMGNFEVcMUjXqUkQYglK3gkaEwVXzUkQggCRRwDZtHUXq0jLhc1XVkEUqcjXqASZHcGRBgzbM0FV3fjPNYGRBgjbM0FV3fjTKcGRn8zM5QkTDslZTsFLVgkcAckVzMVLPASRsM1ZAIkVzEzUioGNUE1azX0Sn4RZKYGRBgzazXjXvDkLWMWQFQFNHIES3IVZKYGRBgTcUczXkAiUZQGLogjcyHDSn4BdgASTxb0bEYDY3fjTLgmXosjcHIDR4clUXYWUV8DZtj1R1gjPHk2ZWE1bUYzX3s1UOglKosDLHIDRns1QhcVSxHFNHIDSn4BZX8VPxDlbEwlX3fjPLg1Mn8zM2H0TIEEURIUUVE1YAcjXuQSLYUDMFMFdq01S2nGURQzZpQ0ZvXEV1EzUZQ2XVEEcQ0lXzDjTYQWQrgkbUYTV3fjTLglKBI1YIcEVyUkQisVRWIkZvjFRyUjUZQWVvDlbUcUXqkjPHk1YVgEczXUVxASZHcmXogjY5YUV40zUX0VUFUEMAcUV3fjTLglKREVdIY0SnIVZHYlcwHFZvjFRyQTZHkicSMURQQkTRUkUgcVPGI1azDSVCUUahESUFgzazXjXvDkLWM2ZrEFNHIDSz4RZHYlZrElcUczXkAiUXMCLogzcHkWSz4RZHY1MVMld3TUXuQiUOglKosjcHIDR0U0QiUFLVg0LvjFR2gTdMQmKogjYLcjVmEzUYgCRBwDctjFRlwzUjMGLVkkdIcEY3fjPLQGUogjYHYEY1UTLhkGLogjcHIDRnslQhU2cVgEdvjFR1gDdKkic4sTSqQTTIkTUYMWQFIlcqwVXsUkZgoWRWQVN1M0TIEEURIUUVE1YAcjXuQSLYUDMFMFdqcDRqQiUXg1cVkkZvjFR2gjPHYWQrI1YvXUV5UEahkTTV8DZtbEVzEDLgoWRBgTZmYEVzQiUYIGLogzchkFRlomUYkWSWgUaUYTUzDzUYgCRRwDZtHUX4kjUOgFQCwDZtHTX4kjUOgldRwDZyLzSMsFQQkTRUk0bEYjX1sFag0VSTMFdYcUVloFagYWUGMVYvXkVzASZHY2LBwDZtHkVzEzUioGNUE1Ymc0SnQTZLIyLBwDZtfWXvDkLWM2ZrEFNHIDSz4RZHY1MVMld3TUXmc1UOgFQowjLyHDSn4Bdh4VQFI1ZvjFR1MiPLglK3IFMvXUXqEUahQCLogjcyHUSn4BZXQSPWgUdMc0Sn4RZHYFRVokc3XTXmkzUOglKogTcyLzS0oGURQzZpQ0ZvXEV1EzUZQ2XVEEcQ0lXzPyPO0zZDEURIUUVyUjQhY2ZrEVaUoVX5kzUjYFUrE1YIYTXqEkUOgFQogjYtbEV3UjUgsVTWkEdqQTV3fDZhsVVWkEdIY0TucVaHYFSFo0YzvVXqcmUOgFQ40DZtHUXq0jLhc1XVkEUqcjXqASZHcGRBgzbM0FV3fjTNYGRBgjbM0FV3fjTKcGRn8zM5QkTDslZTsFLVgkcAckVzMVLPASRsM1ZAIkVzEzUioGNUE1azX0Sn4RZKYGRBgzazXjXvDkLWMWQFQFNHIES3IVZKYGRBgTcUczXkAiUZQGLogjcyHDSn4BdgASTxb0bEYDY3fjTLgmXosjcHIDR4clUXYWUV8DZtj1R1gjPHk2ZWE1bUYzX3s1UOglKosDLHIDRns1QhcVSxHFNHIDSn4BZX8VPxDlbEwlX3fjPLg1Mn8zM2H0TIEEURIUUVE1YAcjXuQSLYUDMFMFdq01S2nGURQzZpQ0ZvXEV1EzUZQ2XVEEcQ0lXzDjTYQWQrgkbUYTV3fjTLglKBI1YIcEVyUkQisVRWIkZvjFRm0TLXMUTWQlbUwFRlwjQZcFMrE1Z2Y0SnQTdMglKRE1ZMIiXmMlUYQ0ZGI1ZvjFR2gjPHMWSsgENHIESyfjPHIWSsgENHI0R2gDZOcidTIEQqoFUqAiUXYWPWoEciECTvjTaisVPRoEcAc0X5gSUg8FMV8DZtj1R1gjPH8FMFIFLQIyUyUjQjgCRRwDdhk1R1gjPHUWUGMVYvXkVzASZHY2LBwDZtfWXvDkLWMWQFQFNHIES3IVZKYGRBgTdmYEV1UkUOglKosjcHIDR4s1UgMWUFMFdqc0Sn4RZKACRBgDZqcjXm0jLhgCRBwDZtfFVuEjLgIWQrIFNHIDSncCZOcyMRMURQQkTRUkUgcVPGI1azDSVEQiQig2Zs8zM5QkTDslZTsFLVgkcAckVzMlUQQWTsIFMAIUVzUDaXIWUFkENHIESn4hPhcVRWg0bUYzXqkzURoFLogTdUIiX5UjUZQWRBgTZmYEVzQiUYIGLogzchkFRlomUYkWSWgUaUYTUzDzUYgCRRwDZtHUX4kjUOgFVC0DZtHTX4kjUOgldRwDZyLzSMsFQQkTRUk0bEYjX1sFag0VSTMFdYcUVloFagYWUGMVYvXkVzASZHY2LBwDZtHkVzEzUioGNUE1Ymc0SnQTZLIyLBwDZtfWXvDkLWM2ZrEFNHIESz4RZHY1MVMld3TUXmc1UOgFQowjLyHDSn4Bdh4VQFI1ZvjFR1MiTNQiKCwjctLDS1o1TMkGV40jdLkFSn4BdhQCLVE1ZQ0lXz.SZHY2LR0DZtfFVzDzUXkWSW8DZtjFRlgjUZYGNFE1YIc0Sn4RZHU2LC8Tc5QkTDslZTsFLVgkcAckVzMlUQQWTsIFMzLzSMsFQQkTRUk0bEYjX1sFag0VUpEldIcEYlQEagcVRFE1ZQY0SnQTZHYlKWgEdEYUXqE0UYg2ZDkENHIDUu8VajQENrE1ZIIDRoclUXQGMVkkbvjFR2IVZHYldVkUdMcEVsUkQUQSPWkENHIESn4hTgkWRV8DZDkVSn4hPgkWRV8DZ5IESnMyPO0zZDEURIUUVyUjQhY2ZrEVaMQ0X3k0UYYlZrElcUczXkAiUZQGLogjcyHDSn4hTZQWPWMld3TUXmc1UOgFQowjLyHDSn4BdgASTxb0bqwVX3fjPLQmKogjY2X0X5gSUgc1YW8DZDkFSxLiPLglK3IlaEYjXqASZHY2LBwDZtfmXz.iUgsVTsIFMvjFR1MiTMglKngEMAcEV40zUOglKogjYHYkV1giQgcVRW8DZtjFR0MyPOUmdTIEQqoFUqAiUXYWPWoEciYUTzEUahQCMC8TSqQTTIkTUYMWQFIlcqwVXsUkZgoWRWQlYTwVXmkjQgsVTV8DZDkFRl4xUXgWQVE1ZQcUV3sFQYgCRBIVc2YEY1cVLgQ2ZGQ0YIcEVykjPHk1YVgEczXUVxASZHcmXogjY5YUV40zUX0VUFUEMAcUV3fjTLglKREVdIY0SnY1TLglKBEVdIY0SnomTLg1LC8TSqQTTIkTUYMWQFIlcqwVXs0DUigWVWkkYpwVX1U0QiUFLVoEcvjFR1MiPLglKRoEcAc0X5gSUgc1YW8DZDkFSxLiPLglK3EFLQIyUysFaggCRBwDctjFRlciUioGNUE1Ymc0SnQTZLIyLBwDZtfmXtUjQhsFLogjcyHDSn4BdhQCLVE1ZQ0lXz.SZHY2LR0DZtfFVzDzUXkWSW8DZtjFRlgjUZYGNFE1YIc0Sn4RZHU2LC8Tc5QkTDslZTsFLVgkcAckVzMlUQQWTsIFMzLzSMsFQQkTRUk0bEYjX1sFag0VUpEldIcEYlQEagcVRFE1ZQY0SnQTZHYlKWgEdEYUXqE0UYg2ZDkENHIjVmkzUgUGMVoUZMcDUmkzUXMWRBgTZmYEVzQiUYIGLogzchkFRlomUYkWSWgUaUYTUzDzUYgCRRwDZtHUX4kjUOglXC4DZtHTX4kjUOgldRwDZyLzSMsFQQkTRUk0bEYjX1sFag0VSTMFdYcUVloFagYWUGMVYvXkVzASZHY2LBwDZtHkVzEzUioGNUE1Ymc0SnQTZLIyLBwDZtfWXvDkLWM2ZrEFNHIDSz4RZHY1MVMld3TUXmc1UOgFQowjLyHDSn4Bdh4VQFI1ZvjFR1MiPLglK3IFMvXUXqEUahQCLogjcyHUSn4BZXQSPWgUdMc0Sn4RZHYFRVokc3XTXmkzUOglKogTcyLzS0oGURQzZpQ0ZvXEV1EzUZQ2XVEEcQ0lXzPyPO0zZDEURIUUVyUjQhY2ZrEVaUoVX5kzUjYFUrE1YIYTXqEkUOgFQogjYtbEV3UjUgsVTWkEdqQTV3fjPigWUVEVc2ESXPUDahcFLrgjYLYjVmQCags1cV8DZDkFRlomUYkWSWgUaUYTUzDzUYgCRRwDZtHUX4kjUOglXS4DZtHTX4kjUOgldRwDZyLzSMsFQQkTRUk0bEYjX1sFag0VSTMFdYcUVloFagYWUGMVYvXkVzASZHY2LBwDZtHkVzEzUioGNUE1Ymc0SnQTZLIyLBwDZtfWXvDkLWM2ZrEFNHIDSz4RZHY1MVMld3TUXmc1UOgFQowjLyHDSn4Bdh4VQFI1ZvjFR1MiPLglK3IFMvXUXqEUahQCLogjcyHUSn4BZXQSPWgUdMc0Sn4RZHYFRVokc3XTXmkzUOglKogTcyLzS0oGURQzZpQ0ZvXEV1EzUZQ2XVEEcQ0lXzPyPO0zZDEURIUUVyUjQhY2ZrEVaUoVX5kzUjYFUrE1YIYTXqEkUOglKogjYtbEV3UjUgsVTWkEdqQTV3fDZis1cwDVZqYzXzjjPHk1YVgEczXUVxASZHcmXogjY5YUV40zUX0VUFUEMAcUV3fjPMglKREVdIY0SnomTLglKBEVdIY0SnomTLg1LC8TSqQTTIkTUYMWQFIlcqwVXs0DUigWVWkkYpwVX1U0QiUFLVoEcvjFR1MiPLglKRoEcAc0X5gSUgc1YW8DZDkFSxLiPLglK3EFLQIyUysFaggCRRwDctjFRlciUioGNUE1Ymc0SnQTZLIyLBwDZtfmXtUjQhsFLogjcyHDSn4BdhQCLVE1ZQ0lXz.SZHY2LR0DZtfFVzDzUXkWSW8DZDkFRlgjUZYGNFE1YIc0Sn4RZHU2LC8Tc5QkTDslZTsFLVgkcAckVzMlUQQWTsIFMzLzS0oGURQzZpQ0ZvXEV1EzUZQ2XFU0YIYTXqQyPOUmdVokZqYUXmEzQh8FMwjUN1MUXu0DahUWTWMFcqwVXsQyPOYWQrI1YvDiX4X2PTETRUAUSAIkVpASZHM2ZwfEd3XTUvPiUZQ2XrQUc3XzXn4BZic1cVM1ZvjFR1MiPLg1Mn8zMtTETRUDUSYlZFkENHIUXu0DahUWTWMFcqwVXsgSQLglKnM1Y2Y0XqASZHMGUCwDctjFR0MyPOAUQpQUPvPDRuEkUOgldVoUZIISX5UUag8FMwjUYEkFRlg0UXIWUWkENHI0Rv3RZKYGR3sTN1MDUAkTUP0TPRokZvjFRysVLXgGNFMFLzXkVzMVLWcmKogjYXcEVxU0UYgCRRsDLtj1R1gDdKkicCQUPIUETMEjTZoFLogzbqECV3giQiACMVoEciEyU2QTZHYFVWgkbUcUV3fjTKAiKosjcHg2R4X2PTETRUAUSAIkVpASZHM2ZwfEd3XzXvPiUZQ2XwbEdHIDRwTjQgASUV8DZ5IUS1MiPLg1Mn8zMtTETRUDUSYlZFkENHIUXu0DahUWTWMFcqwVXsgCLLglKnM1Y2Y0XqASZHMGUCwDctjFR0MyPOAUQpQUPvPDRuEkUOgldVoUZIISX5UUag8FMwjUYQkFRlg0UXIWUWkENHI0Rv3RZKYGR3sTN1MDUAkTUP0TPRokZvjFRysVLXgGNFMFLzXkVzMVLWACRBgTLEYTXvTkUOgldR0jcyHDSncCZOciKUAkTEQ0TlolQYgCRRE1aMwlX0E0UiQ2ZrEVa3rVSn4BZic1cVM1ZvjFRyQ0PLQmKogTcyLzSPUjZTEDLDgzaQY0SnomUZkVRxDldU0VXuQSLYU1XogjYXcEVxU0UYgCRRsDLtj1R1gDdKkicCQUPIUETMEjTZoFLogzbqECV3giQiACMVoEciEyUyfjPHESQFEFLUY0SnomTMY2LBwDZ2f1S23RUPIUQTMkYpYTV3fjTg8VSrIVcQc0XzsFag0FNU4DZtf1XmcmUisFLogzbTMDSz4RZHU2LC8DTEoFUAACQH8VTV8DZ5YzX4E0UXoWUxHVYAkFRlg0UXIWUWkENHIDSz4RZHU2LC8DTEoFUAACQH8VTV8DZ5YzX4E0UXoWUxHVYEkFRlg0UXIWUWkENHIDSz4RZHU2LC8DTEoFUAACQH8VTV8DZ5YzX4E0UXoWUxHVYEMDSn4BZic1cVM1ZvjFR1MiPLg1Mn8zMtTETRUDUSYlZFkENHIUX50zQicVTWMVd3TES2gjPHESQFEFLUY0Sn4RZKYGR3sTN1MDUAkTUP0TPRokZvjFRyEkLhoWQFMFLMIyU3gjPHESQFEFLUY0Sn4RZKYGR3sTN1MDUAkTUP0TPRokZvjFRyEkLhoWQFMFLMIyU4gjPHESQFEFLUY0Sn4RZKYGR3sTN1MDUAkTUP0TPRokZvjFRyEkLhoWQFMFLMIyU5gjPHESQFEFLUY0Sn4RZKYGR3sTN1MDUAkTUP0TPRokZvjFRyEkLhoWQFMFLMIyUvfjPHESQFEFLUY0Sn4RZKYGR3sTN1MDUAkTUP0TPRokZvjFRyEkLhoWQFMFLMIyUwfjPHESQFEFLUY0Sn4RZKYGR3sTN1MDUAkTUP0TPRokZvjFRyEkLhoWQFMFLMIyUxfjPHESQFEFLUY0Sn4RZKYGR3sTN1MDUAkTUP0TPRokZvjFRyEkLhoWQFMFLMIyUyfjPHESQFEFLUY0Sn4RZKYGR3sTN1MDUAkTUP0TPRokZvjFRyEkLhoWQFMFLMIyUzfjPHESQFEFLUY0Sn4RZKYGR3sTN1MDUAkTUP0TPRokZvjFR5UkUgYWUrI1YvvFRlg0UXIWUWkENHIDSz4RZHU2LC8TctbEV3UjUgkGMC8jcIcUV4UkQikGMC8jcIcUV4UkQiYFSGEVcQ01Tv.CaXsVRW8DZDkFR4XWZgUWTWkkYpYTV3fjPLglK3IldEYzXvzzUOglKogjYXcEVxU0UYgCRRsDLtjFRlMSLgoWUrM0YvXUV3fDdPg1Mn8zMyDSX5UkQH8VTV8DZDkFRlwzQicVTWMVdvjFR1gjPHESQFEFLUY0SnomTMYGRBgDc3XzXqQCUXMWUV8DZLoGRncCZOcyLwDldUYDRuEkUOgFRogjYLczXmE0UikGLogjcHIDRwTjQgASUV8DZ5IUS1gjPHQGNFM1ZzPEVyUkUOgFTpgTcyLzSzgiQisVPRokZvjFR4gjPHkWTWgkdUIiX3fjPLglKnM1Y2Y0XqASZHMGUCwDZtfVX0E0UY4TQVE1ZvjFRD0DZHU2LC8Dc3XzXqEjTZoFLogjdHIDR4E0UXoWUxHFNHIDSn4BZic1cVM1ZvjFRyQ0PLglKnEVcQcUVNUjUgsFLogTQIg2R4XWZgUWTWkkYpYTV3fjTMglK3IldEYzXvzzUOglKogjYXcEVxU0UYgCRRsDLtjFRlMSLgoWUrM0YvXUV3fDZQg1Mn8zMyDSX5UkQH8VTV8DZXkFRlwzQicVTWMVdvjFR1gjPHESQFEFLUY0SnomTMYGRBgDc3XzXqQCUXMWUV8DZXoGRncCZOcyLwDldUYDRuEkUOglXogjYLczXmE0UikGLogjcHIDRwTjQgASUV8DZ5IUS1gjPHQGNFM1ZzPEVyUkUOglXpgTcyLzSzgiQisVPRokZvjFRyfjPHkWTWgkdUIiX3fjPLglKnM1Y2Y0XqASZHMGUCwDZtfVX0E0UY4TQVE1ZvjFRG0DZHU2LC8Dc3XzXqEjTZoFLogDMHIDR4E0UXoWUxHFNHIDSn4BZic1cVM1ZvjFRyQ0PLglKnEVcQcUVNUjUgsFLogTPIg2R4XWZgUWTWkkYpYTV3fjTLYGRBgTdQcEV5UkLhgCRBwDZtf1XmcmUisFLogzbTMDSn4BZgUWTWkkSEYUXqASZHETSngTcyLzSzgiQisVPRokZvjFR2QTZHYFSGM1YQc0X4ASZHYGRBgTLEYTXvTkUOgldR0jcHIDRzgiQisFMTg0bUY0SngjZHU2LC8TctzlXq0zUYoGMC8jcIcUV4UkQiYFSGEVcQ01Tv.CaXsVRW8DZHkFR4XWZgUWTWkkYpYTV3fjPLglK3IldEYzXvzzUOglKogjYXcEVxU0UYgCRRsDLtjFRlMSLgoWUrM0YvXUV3fDdPg1Mn8zMyDSX5UkQH8VTV8DZDkFRlwzQicVTWMVdvjFR1gjPHESQFEFLUY0SnomTMYGRBgDc3XzXqQCUXMWUV8DZLoGRncCZOcyLwDldUYDRuEkUOgFRogjYLczXmE0UikGLogjcHIDRwTjQgASUV8DZ5IUS1gjPHQGNFM1ZzPEVyUkUOgFTpgTcyLzSzgiQisVPRokZvjFR4gjPHkWTWgkdUIiX3fjPLglKnM1Y2Y0XqASZHMGUCwDZtfVX0E0UY4TQVE1ZvjFRD0DZHU2LC8Dc3XzXqEjTZoFLogjdHIDR4E0UXoWUxHFNHIDSn4BZic1cVM1ZvjFRyQ0PLglKnEVcQcUVNUjUgsFLogTQIg2R4XWZgUWTWkkYpYTV3fjTMglK3IldEYzXvzzUOglKogjYXcEVxU0UYgCRRsDLtjFRlMSLgoWUrM0YvXUV3fDZQg1Mn8zMyDSX5UkQH8VTV8DZXkFRlwzQicVTWMVdvjFR1gjPHESQFEFLUY0SnomTMYGRBgDc3XzXqQCUXMWUV8DZXoGRncCZOcyLwDldUYDRuEkUOglXogjYLczXmE0UikGLogjcHIDRwTjQgASUV8DZ5IUS1gjPHQGNFM1ZzPEVyUkUOglXpgTcyLzSzgiQisVPRokZvjFRyfjPHkWTWgkdUIiX3fjPLglKnM1Y2Y0XqASZHMGUCwDZtfVX0E0UY4TQVE1ZvjFRG0DZHU2LC8Dc3XzXqEjTZoFLogDMHIDR4E0UXoWUxHFNHIDSn4BZic1cVM1ZvjFRyQ0PLglKnEVcQcUVNUjUgsFLogTPIg2R4XWZgUWTWkkYpYTV3fjTLYGRBgTdQcEV5UkLhgCRBwDZtf1XmcmUisFLogzbTMDSn4BZgUWTWkkSEYUXqASZHETSngTcyLzSzgiQisVPRokZvjFR2QTZHYFSGM1YQc0X4ASZHYGRBgTLEYTXvTkUOgldR0jcHIDRzgiQisFMTg0bUY0SngjZHU2LC8TctzlXq0zUYoGMC8jcIcUV4UkQiYFSGEVcQ01Tv.CaXsVRW8DZLkFR4XWZgUWTWkkYpYTV3fjPLglK3IldEYzXvzzUOglKogjYXcEVxU0UYgCRRsDLtjFRlMSLgoWUrM0YvXUV3fDdPg1Mn8zMyDSX5UkQH8VTV8DZDkFRlwzQicVTWMVdvjFR1gjPHESQFEFLUY0SnomTMYGRBgDc3XzXqQCUXMWUV8DZLoGRncCZOcyLwDldUYDRuEkUOgFRogjYLczXmE0UikGLogjcHIDRwTjQgASUV8DZ5IUS1gjPHQGNFM1ZzPEVyUkUOgFTpgTcyLzSzgiQisVPRokZvjFR4gjPHkWTWgkdUIiX3fjPLglKnM1Y2Y0XqASZHMGUCwDZtfVX0E0UY4TQVE1ZvjFRD0DZHU2LC8Dc3XzXqEjTZoFLogjdHIDR4E0UXoWUxHFNHIDSn4BZic1cVM1ZvjFRyQ0PLglKnEVcQcUVNUjUgsFLogTQIg2R4XWZgUWTWkkYpYTV3fjTMglK3IldEYzXvzzUOglKogjYXcEVxU0UYgCRRsDLtjFRlMSLgoWUrM0YvXUV3fDZQg1Mn8zMyDSX5UkQH8VTV8DZXkFRlwzQicVTWMVdvjFR1gjPHESQFEFLUY0SnomTMYGRBgDc3XzXqQCUXMWUV8DZXoGRncCZOcyLwDldUYDRuEkUOglXogjYLczXmE0UikGLogjcHIDRwTjQgASUV8DZ5IUS1gjPHQGNFM1ZzPEVyUkUOglXpgTcyLzSzgiQisVPRokZvjFRyfjPHkWTWgkdUIiX3fjPLglKnM1Y2Y0XqASZHMGUCwDZtfVX0E0UY4TQVE1ZvjFRG0DZHU2LC8Dc3XzXqEjTZoFLogDMHIDR4E0UXoWUxHFNHIDSn4BZic1cVM1ZvjFRyQ0PLglKnEVcQcUVNUjUgsFLogTPIg2R4XWZgUWTWkkYpYTV3fjTLYGRBgTdQcEV5UkLhgCRBwDZtf1XmcmUisFLogzbTMDSn4BZgUWTWkkSEYUXqASZHETSngTcyLzSzgiQisVPRokZvjFR2QTZHYFSGM1YQc0X4ASZHYGRBgTLEYTXvTkUOgldR0jcHIDRzgiQisFMTg0bUY0SngjZHU2LC8TctzlXq0zUYoGMC8jcIcUV4UkQiYFSGEVcQ01Tv.CaXsVRW8DZPkFR4XWZgUWTWkkYpYTV3fjPLglK3IldEYzXvzzUOglKogjYXcEVxU0UYgCRRsDLtjFRlMSLgoWUrM0YvXUV3fDdPg1Mn8zMyDSX5UkQH8VTV8DZDkFRlwzQicVTWMVdvjFR1gjPHESQFEFLUY0SnomTMYGRBgDc3XzXqQCUXMWUV8DZLoGRncCZOcyLwDldUYDRuEkUOgFRogjYLczXmE0UikGLogjcHIDRwTjQgASUV8DZ5IUS1gjPHQGNFM1ZzPEVyUkUOgFTpgTcyLzSzgiQisVPRokZvjFR4gjPHkWTWgkdUIiX3fjPLglKnM1Y2Y0XqASZHMGUCwDZtfVX0E0UY4TQVE1ZvjFRD0DZHU2LC8Dc3XzXqEjTZoFLogjdHIDR4E0UXoWUxHFNHIDSn4BZic1cVM1ZvjFRyQ0PLglKnEVcQcUVNUjUgsFLogTQIg2R4XWZgUWTWkkYpYTV3fjTMglK3IldEYzXvzzUOglKogjYXcEVxU0UYgCRRsDLtjFRlMSLgoWUrM0YvXUV3fDZQg1Mn8zMyDSX5UkQH8VTV8DZXkFRlwzQicVTWMVdvjFR1gjPHESQFEFLUY0SnomTMYGRBgDc3XzXqQCUXMWUV8DZXoGRncCZOcyLwDldUYDRuEkUOglXogjYLczXmE0UikGLogjcHIDRwTjQgASUV8DZ5IUS1gjPHQGNFM1ZzPEVyUkUOglXpgTcyLzSzgiQisVPRokZvjFRyfjPHkWTWgkdUIiX3fjPLglKnM1Y2Y0XqASZHMGUCwDZtfVX0E0UY4TQVE1ZvjFRG0DZHU2LC8Dc3XzXqEjTZoFLogDMHIDR4E0UXoWUxHFNHIDSn4BZic1cVM1ZvjFRyQ0PLglKnEVcQcUVNUjUgsFLogTPIg2R4XWZgUWTWkkYpYTV3fjTLYGRBgTdQcEV5UkLhgCRBwDZtf1XmcmUisFLogzbTMDSn4BZgUWTWkkSEYUXqASZHETSngTcyLzSzgiQisVPRokZvjFR2QTZHYFSGM1YQc0X4ASZHYGRBgTLEYTXvTkUOgldR0jcHIDRzgiQisFMTg0bUY0SngjZHU2LC8TctzlXq0zUYoGMC8jcIcUV4UkQiYFSGEVcQ01Tv.CaXsVRW8DZTkFR4XWZgUWTWkkYpYTV3fjPLglK3IldEYzXvzzUOglKogjYXcEVxU0UYgCRRsDLtjFRlMSLgoWUrM0YvXUV3fDdPg1Mn8zMyDSX5UkQH8VTV8DZDkFRlwzQicVTWMVdvjFR1gjPHESQFEFLUY0SnomTMYGRBgDc3XzXqQCUXMWUV8DZLoGRncCZOcyLwDldUYDRuEkUOgFRogjYLczXmE0UikGLogjcHIDRwTjQgASUV8DZ5IUS1gjPHQGNFM1ZzPEVyUkUOgFTpgTcyLzSzgiQisVPRokZvjFR4gjPHkWTWgkdUIiX3fjPLglKnM1Y2Y0XqASZHMGUCwDZtfVX0E0UY4TQVE1ZvjFRD0DZHU2LC8Dc3XzXqEjTZoFLogjdHIDR4E0UXoWUxHFNHIDSn4BZic1cVM1ZvjFRyQ0PLglKnEVcQcUVNUjUgsFLogTQIg2R4XWZgUWTWkkYpYTV3fjTMglK3IldEYzXvzzUOglKogjYXcEVxU0UYgCRRsDLtjFRlMSLgoWUrM0YvXUV3fDZQg1Mn8zMyDSX5UkQH8VTV8DZXkFRlwzQicVTWMVdvjFR1gjPHESQFEFLUY0SnomTMYGRBgDc3XzXqQCUXMWUV8DZXoGRncCZOcyLwDldUYDRuEkUOglXogjYLczXmE0UikGLogjcHIDRwTjQgASUV8DZ5IUS1gjPHQGNFM1ZzPEVyUkUOglXpgTcyLzSzgiQisVPRokZvjFRyfjPHkWTWgkdUIiX3fjPLglKnM1Y2Y0XqASZHMGUCwDZtfVX0E0UY4TQVE1ZvjFRG0DZHU2LC8Dc3XzXqEjTZoFLogDMHIDR4E0UXoWUxHFNHIDSn4BZic1cVM1ZvjFRyQ0PLglKnEVcQcUVNUjUgsFLogTPIg2R4XWZgUWTWkkYpYTV3fjTLYGRBgTdQcEV5UkLhgCRBwDZtf1XmcmUisFLogzbTMDSn4BZgUWTWkkSEYUXqASZHETSngTcyLzSzgiQisVPRokZvjFR2QTZHYFSGM1YQc0X4ASZHYGRBgTLEYTXvTkUOgldR0jcHIDRzgiQisFMTg0bUY0SngjZHU2LC8TctzlXq0zUYoGMC8jcIcUV4UkQiYFSGEVcQ01Tv.CaXsVRW8DZXkFR4XWZgUWTWkkYpYTV3fjPLglK3IldEYzXvzzUOglKogjYXcEVxU0UYgCRRsDLtjFRlMSLgoWUrM0YvXUV3fDdPg1Mn8zMyDSX5UkQH8VTV8DZDkFRlwzQicVTWMVdvjFR1gjPHESQFEFLUY0SnomTMYGRBgDc3XzXqQCUXMWUV8DZLoGRncCZOcyLwDldUYDRuEkUOgFRogjYLczXmE0UikGLogjcHIDRwTjQgASUV8DZ5IUS1gjPHQGNFM1ZzPEVyUkUOgFTpgTcyLzSzgiQisVPRokZvjFR4gjPHkWTWgkdUIiX3fjPLglKnM1Y2Y0XqASZHMGUCwDZtfVX0E0UY4TQVE1ZvjFRD0DZHU2LC8Dc3XzXqEjTZoFLogjdHIDR4E0UXoWUxHFNHIDSn4BZic1cVM1ZvjFRyQ0PLglKnEVcQcUVNUjUgsFLogTQIg2R4XWZgUWTWkkYpYTV3fjTMglK3IldEYzXvzzUOglKogjYXcEVxU0UYgCRRsDLtjFRlMSLgoWUrM0YvXUV3fDZQg1Mn8zMyDSX5UkQH8VTV8DZXkFRlwzQicVTWMVdvjFR1gjPHESQFEFLUY0SnomTMYGRBgDc3XzXqQCUXMWUV8DZXoGRncCZOcyLwDldUYDRuEkUOglXogjYLczXmE0UikGLogjcHIDRwTjQgASUV8DZ5IUS1gjPHQGNFM1ZzPEVyUkUOglXpgTcyLzSzgiQisVPRokZvjFRyfjPHkWTWgkdUIiX3fjPLglKnM1Y2Y0XqASZHMGUCwDZtfVX0E0UY4TQVE1ZvjFRG0DZHU2LC8Dc3XzXqEjTZoFLogDMHIDR4E0UXoWUxHFNHIDSn4BZic1cVM1ZvjFRyQ0PLglKnEVcQcUVNUjUgsFLogTPIg2R4XWZgUWTWkkYpYTV3fjTLYGRBgTdQcEV5UkLhgCRBwDZtf1XmcmUisFLogzbTMDSn4BZgUWTWkkSEYUXqASZHETSngTcyLzSzgiQisVPRokZvjFR2QTZHYFSGM1YQc0X4ASZHYGRBgTLEYTXvTkUOgldR0jcHIDRzgiQisFMTg0bUY0SngjZHU2LC8TctzlXq0zUYoGMC8jcIcUV4UkQiYFSGEVcQ01Tv.CaXsVRW8DZhkFR4XWZgUWTWkkYpYTV3fjPLglK3IldEYzXvzzUOglKogjYXcEVxU0UYgCRRsDLtjFRlMSLgoWUrM0YvXUV3fDdPg1Mn8zMyDSX5UkQH8VTV8DZDkFRlwzQicVTWMVdvjFR1gjPHESQFEFLUY0SnomTMYGRBgDc3XzXqQCUXMWUV8DZLoGRncCZOcyLwDldUYDRuEkUOgFRogjYLczXmE0UikGLogjcHIDRwTjQgASUV8DZ5IUS1gjPHQGNFM1ZzPEVyUkUOgFTpgTcyLzSzgiQisVPRokZvjFR4gjPHkWTWgkdUIiX3fjPLglKnM1Y2Y0XqASZHMGUCwDZtfVX0E0UY4TQVE1ZvjFRD0DZHU2LC8Dc3XzXqEjTZoFLogjdHIDR4E0UXoWUxHFNHIDSn4BZic1cVM1ZvjFRyQ0PLglKnEVcQcUVNUjUgsFLogTQIg2R4XWZgUWTWkkYpYTV3fjTMglK3IldEYzXvzzUOglKogjYXcEVxU0UYgCRRsDLtjFRlMSLgoWUrM0YvXUV3fDZQg1Mn8zMyDSX5UkQH8VTV8DZXkFRlwzQicVTWMVdvjFR1gjPHESQFEFLUY0SnomTMYGRBgDc3XzXqQCUXMWUV8DZXoGRncCZOcyLwDldUYDRuEkUOglXogjYLczXmE0UikGLogjcHIDRwTjQgASUV8DZ5IUS1gjPHQGNFM1ZzPEVyUkUOglXpgTcyLzSzgiQisVPRokZvjFRyfjPHkWTWgkdUIiX3fjPLglKnM1Y2Y0XqASZHMGUCwDZtfVX0E0UY4TQVE1ZvjFRG0DZHU2LC8Dc3XzXqEjTZoFLogDMHIDR4E0UXoWUxHFNHIDSn4BZic1cVM1ZvjFRyQ0PLglKnEVcQcUVNUjUgsFLogTPIg2R4XWZgUWTWkkYpYTV3fjTLYGRBgTdQcEV5UkLhgCRBwDZtf1XmcmUisFLogzbTMDSn4BZgUWTWkkSEYUXqASZHETSngTcyLzSzgiQisVPRokZvjFR2QTZHYFSGM1YQc0X4ASZHYGRBgTLEYTXvTkUOgldR0jcHIDRzgiQisFMTg0bUY0SngjZHU2LC8TctzlXq0zUYoGMC8TctzlXq0zUYoWSs8zM2HUXu0DahUWTWMFcqwVXsQyPOgGNwD1bMckVyU0QgcVTxDFdzLzS1UDahcFLwHVN1MDUAkTUP0TPRokZvjFR3gSLgMWUpE1YIYTXqEEaHYFVWgkbUcUV3fjTLQmKogTcyLzS04xUXgWQVEVdzLzSRgSLgMWSWM0YzXEVsUEahkicoQUc3XUX4QyPOIENwD1bAIkVpASZHkWTWMlZqESXAgyZhUGNVEFZtfVXmAiUYgCR3QkdUcTVugSLWETRBgDLMcUV3ASZHYGRBgzZQYkV5UDaXIWUV8DZDkFRlQTLXo2ZrM1ZvjFR2gDZOciKUgEdEYUXqE0UYgWSs8zMtTEV3UjUgsVTWkEdAIjXmkzUXMWUFM1ZIckTpASZHgGNwD1bMUkV0TULhglKnM1Y2Y0XqASZHAyLBwDZ2f1S23RUXgWQVE1ZQcUV3EjPhcVRWg0bUYzXqkzURoFLogDd3DSXyUjZXkGNrIlcQckV0QiUScVTWkEdqYEVx0TaHYFVWgkbUcUV3fjTLQmKogTcyLzSPUDahcFLVkkdUwlXl4xUXgWQVE1ZQcUV3sFQYgCRnIVc3XUXLsVLhoWUrE1ZIcDU00zUZo2ZwDFcIIDRwTjQgASUV8DZTk1R1gDdKkicCQ0YIcEVyUkQisVRGgjcEwlXmAiUYoWUrIVRQY0SngjLgUGLwPUcU0lXoUkQQs1cVgEMvnWXpUEaHYFVWgkbUcUV3fjPLQmKogTcyLzSPUDahcFLVkkdUwlXl4xUXgWQVE1ZQcUV3sFQYgCRnIVc3XUXMgiQYAycVgkdqESXzgiZg8TVrkEZtf1XmcmUisFLogzcyHDSncCZOciKUgEdEYUXqE0UYgWPBI1YIcEVyUkQisVRWIkZvjFR3gSLgMWTToUdQcEVz0jUYITUFMlLUYUVzACUZkVSsgjYXcEVxU0UYgCRRwjLyHDSncCZOciKUgEdEYUXqE0UYgWPBI1YIcEVyUkQisVRWIkZvjFR3gSLgMWQTEFZqYUVz0jUYEDLwDFLzXzXn4BZic1cVM1ZvjFRywTZKYGR3sTN1k2RPUDahcFLVkkdUwlX4QyPOUGRvDVcvv1S2fDLgUGLFgzaQY0SnwzQiASTVoUcIo2U3gSLgMWRBgDcEYUXqASZHMUTWMlZqESXkkjZHYFUxH1ZIc0Sn4RZHYFUFk0aQcEVncmUYgCRRwDZtHEVoE0UZESUV8DZtjFR4X2PTcVRWg0bUYzXqkjLhkicCQ0YIcEVyUkQisVRGgjcEwlXmAiUYoWUrIVRQY0SngjLgUGLwP0aucUV4kjPHESQFEFLUY0SngUZKYGR3sTN1MDUmkzUXMWUFM1ZIcDR1UDahcFLVkkdUwlXIEkUOgFRxDVcvXETn0jLggWPGM1a3vVXMUjQisVRWo0Y2EiXn4BZic1cVM1ZvjFR2MiPLg1Mn8zMtTEV3UjUgsVTWkEdAIjXmkzUXMWUFM1ZIckTpASZHgGNwD1b2QkV4E0UYQWUrIFT3DiXuE0UZUGMrgjYXcEVxU0UYgCR3wDcTMkSzn1TNQiZCwjdXkGS3QUZMMCR3sTN1MDUmkzUXMWUFM1ZIcDR1UDahcFLVkkdUwlXIEkUOgFRxDVcvDCU0UUahkVUFE0Z2YEVz.idgoVUrgjYXcEVxU0UYgCRBwDctjFR0MyPOAUQrI1YvXUV5UEahYlKWgEdEYUXqE0UYg2ZDkENHglX0giUg0DNFkEL2YEV5sVLgQGNpE1SYwVVn4BZic1cVM1ZvjFR2MiPLg1Mn8zMtTEV3UjUgsVTWkEdAIjXmkzUXMWUFM1ZIckTpASZHgGNwD1bQQkV4E0UXQWSVkkPUYzXxTkUYQGLToUZM0FRlg0UXIWUWkENHIESxLiPLg1Mn8zMtTEV3UjUgsVTWkEdAIjXmkzUXMWUFM1ZIckTpASZHgGNwD1bEQUXnslUYQWSVkUPvDSXvPiQiglKnM1Y2Y0XqASZHMGSosjcHg2R4XWdKAUQrI1YvXUV5UEahkGMC8TcHASX0ACaOcCRvDVcvXDRuEkUOgFSGMFLQYkV00jdWgGNwD1bIIDRzUjUgsFLogzTQc0XpsVLgUVSpgjYTIiXqkzUOglKogjYTYTVuE0UXg1cVkENHIESn4hTXkVTWoULUY0Sn4RZHkicCQ0YIcEVyUkQisVRxHVN1MDUmkzUXMWUFM1ZIcDR1UDahcFLVkkdUwlXIEkUOgFRxDVcvDCUu81UYkWRBgTLEYTXvTkUOglXosjcHg2R4X2PTcVRWg0bUYzXqkzQHYWQrI1YvXUV5UEahkTTV8DZHISX0AiUPgVSxDFdAczXugCag0TQFM1ZIckVmcWLhglKnM1Y2Y0XqASZHg2LBwDZ2f1S23RUXgWQVE1ZQcUV3EjPhcVRWg0bUYzXqkzURoFLogDd3DSXycGUZkWTWkEcUwlXPgSLh8VTWoUczvFRlg0UXIWUWkENHgWSz4RZHU2LC8DTEwlXmAiUYoWUrIlYtbEV3UjUgsVTWkEdqQTV3fDZhUGNVE1T3X0X30jUYQTUFE1Yqc0T0EkUYglKnM1Y2Y0XqASZHY2LBwDZ2f1S23RUXgWQVE1ZQcUV3EjPhcVRWg0bUYzXqkzURoFLogDd3DSXyAidgoVUGE1YQckV0QSLSQGNpkEaIIDRwTjQgASUV8DZDk1R1gDdKkicCQ0YIcEVyUkQisVRGgjcEwlXmAiUYoWUrIVRQY0SngjLgUGLFE0aMczXmQSLXsVRTkkdicUVqQiUS8VSwHFZtf1XmcmUisFLogzchk1R1gDdKkicCQ0YIcEVyUkQisVRGgjcEwlXmAiUYoWUrIVRQY0SngjLgUGLVA0bIYkVqQSLXsVQTEVcU0VX5kjPHESQFEFLUY0SnoGdLQmKogTcyLzS04RUXgWQVE1ZQcUV30TaOcyMnQUc3XUX4XWZTUGNVElYpYTV3fDdXIGNwH1ZvPkVogyZhUGNVEFZtfVXmAiUYgCR3Akb3DiXqgSUS8VSwbkT3DSXykjPHASSWkEdvjFR1gjPHsVTVokdEwFVxUkUOglKogjYDECV5sFaisFLogjcHg1S23RUXgWQVE1ZQcUV30TaOciKUgEdEYUXqE0UYgWPBI1YIcEVyUkQisVRWIkZvjFR3gSLgMWSUoUMUEiXn4BZic1cVM1ZvjFR4MiPLg1Mn8zMtTEV3UjUgsVTWkEdAIjXmkzUXMWUFM1ZIckTpASZHgGNwD1bEoFV4gCahYWTWoUczX0TmE0UYg2ZVgkbM0FRlg0UXIWUWkENHIDSz4RZHU2LC8DTEwlXmAiUYoWUrIlYtbEV3UjUgsVTWkEdqQTV3fDZhUGNVEFSqEiX5UEagsVRGQUcMckV5sVLgQWRBgTLEYTXvTkUOgFSosjcHg2R4X2PTcVRWg0bUYzXqkzQHYWQrI1YvXUV5UEahkTTV8DZHISX0ASLTUWUsIVZUYTTqcmUXQCL5ElZUwFRlg0UXIWUWkENHIDSz4RZHU2LC8DTEwlXmAiUYoWUrIlYtbEV3UjUgsVTWkEdqQTV3fDZhUGNVEVS3XTVvbmUXo2ZwDFc3nVXOkEaYglKnM1Y2Y0XqASZHY2LBwDZ2f1S23RUXgWQVE1ZQcUV3EjPhcVRWg0bUYzXqkzURoFLogDd3DSXyEEUZkWTWgEcMYUVBUkQiISUVkEcvPkVo0TaHYFVWgkbUcUV3fjTLIyLBwDZ2f1S23RUXgWQVE1ZQcUV3EjPhcVRWg0bUYzXqkzURoFLogDd3DSXyUDUgg1ZVkEcMYUVAASLgACMFMFZtf1XmcmUisFLogzbpk1R1gDdKkic4sDTEwlXmAiUYoWUrIVdzLzS0gDLgUGLr8zM2fFU0giUgkGMC8TcHASX0ASLh0TQrE1YiYUV3QyPOUGRxDVcvDiXuAiUiIWQFMVcI01S23hLgk2ZFM1a3vVXuQSLYkicCI1YIcEVy0TaOciKUAkTEQ0TlolQYgCRnIVc3XUXSgiUigWSVkUPzDSVxUEaHYFVWgkbUcUV3fjTNY2LBwDZ2f1S23RUPIUQTMkYpYTV3fDZhUGNVE1T3X0X30jUYQzZwHldEwVXoUEaHYFVWgkbUcUV3fDdLQmKogTcyLzS04xUXgWQVEVdzLzS04hLgk2ZFM1a3vVXuQSLYkic4sjcIISXskzUXMGMC8Td3X0X30jUY8FMrkUcAIUXmQiUiwVQwfkdU0lXqkzUOgFQTMlZqESXkAidgoVUFE1azDSVn4hTgc1ZrEFUUYDY5ASZHMTUFElb3vFRlAkLgYWTUk0LQc0SnY1ULglKngUcQczX0AiQUs1YGMFNHIkTN0TQUIEMRwDZtfGV0cWLgASRW8DZXwVVq0jUXoVRogEZtfGV0AiQhUGMVkEcQICUu81UYgCRBwDZtfmXq0jQi8FNrEVS3XTVqASZHYGR3sTN1k2R4M1UXMGMC4hKt3hKt3hKt3hKlIUUMQUTPkzUZESQFM1ZQQEV5UjQtDDQlAEMAcEV40zQtDDQ14hK5EjKt3hKt3hKt3hRUACTEEzZh8VVWgkdUYTTmE0UXwyKIMzasA2atUlaz4COuX0TTMCTrU2Yo41TzEFck4C."
                                    },
                                    "fileref": {
                                        "name": "SWAM Cello 3",
                                        "filename": "SWAM Cello 3_20260430.maxsnap",
                                        "filepath": "~/Documents/Max 9/Snapshots",
                                        "filepos": -1,
                                        "snapshotfileid": "bd5634ba4593571aba6959af3fbfd5e7"
                                    }
                                }
                            ]
                        }
                    },
                    "text": "vst~ \"SWAM Cello 3\"",
                    "varname": "vst~[1]",
                    "viewvisibility": 0
                }
            },
            {
                "box": {
                    "id": "obj-24",
                    "maxclass": "toggle",
                    "numinlets": 1,
                    "numoutlets": 1,
                    "outlettype": [ "int" ],
                    "parameter_enable": 0,
                    "patching_rect": [ 657.0, 626.0, 24.0, 24.0 ]
                }
            },
            {
                "box": {
                    "id": "obj-25",
                    "maxclass": "toggle",
                    "numinlets": 1,
                    "numoutlets": 1,
                    "outlettype": [ "int" ],
                    "parameter_enable": 0,
                    "patching_rect": [ 507.0, 624.0, 24.0, 24.0 ]
                }
            },
            {
                "box": {
                    "id": "obj-30",
                    "maxclass": "toggle",
                    "numinlets": 1,
                    "numoutlets": 1,
                    "outlettype": [ "int" ],
                    "parameter_enable": 0,
                    "patching_rect": [ 448.0, 624.0, 24.0, 24.0 ]
                }
            },
            {
                "box": {
                    "id": "obj-18",
                    "maxclass": "toggle",
                    "numinlets": 1,
                    "numoutlets": 1,
                    "outlettype": [ "int" ],
                    "parameter_enable": 0,
                    "patching_rect": [ 686.0, 626.0, 24.0, 24.0 ]
                }
            },
            {
                "box": {
                    "id": "obj-16",
                    "maxclass": "toggle",
                    "numinlets": 1,
                    "numoutlets": 1,
                    "outlettype": [ "int" ],
                    "parameter_enable": 0,
                    "patching_rect": [ 536.0, 624.0, 24.0, 24.0 ]
                }
            },
            {
                "box": {
                    "id": "obj-9",
                    "maxclass": "toggle",
                    "numinlets": 1,
                    "numoutlets": 1,
                    "outlettype": [ "int" ],
                    "parameter_enable": 0,
                    "patching_rect": [ 477.0, 624.0, 24.0, 24.0 ]
                }
            },
            {
                "box": {
                    "id": "obj-6",
                    "maxclass": "toggle",
                    "numinlets": 1,
                    "numoutlets": 1,
                    "outlettype": [ "int" ],
                    "parameter_enable": 0,
                    "patching_rect": [ 418.0, 624.0, 24.0, 24.0 ]
                }
            },
            {
                "box": {
                    "filename": "onehot.js",
                    "id": "obj-72",
                    "maxclass": "newobj",
                    "numinlets": 1,
                    "numoutlets": 7,
                    "outlettype": [ "", "", "", "", "", "", "" ],
                    "patching_rect": [ 418.0, 596.0, 196.5999999999999, 22.0 ],
                    "saved_object_attributes": {
                        "parameter_enable": 0
                    },
                    "text": "v8 onehot",
                    "textfile": {
                        "filename": "onehot.js",
                        "flags": 0,
                        "embed": 0,
                        "autowatch": 1
                    }
                }
            },
            {
                "box": {
                    "disabled": [ 0, 0, 0, 0, 0, 0, 0 ],
                    "id": "obj-66",
                    "itemtype": 0,
                    "maxclass": "radiogroup",
                    "numinlets": 1,
                    "numoutlets": 1,
                    "outlettype": [ "" ],
                    "parameter_enable": 0,
                    "patching_rect": [ 418.0, 472.0, 24.0, 114.0 ],
                    "shape": 1,
                    "size": 7,
                    "style": "rnbohighcontrast",
                    "value": 0
                }
            },
            {
                "box": {
                    "id": "obj-26",
                    "maxclass": "newobj",
                    "numinlets": 1,
                    "numoutlets": 1,
                    "outlettype": [ "signal" ],
                    "patching_rect": [ 118.0, 82.0, 46.0, 22.0 ],
                    "text": "r~ out2"
                }
            },
            {
                "box": {
                    "id": "obj-11",
                    "maxclass": "newobj",
                    "numinlets": 1,
                    "numoutlets": 1,
                    "outlettype": [ "signal" ],
                    "patching_rect": [ 47.0, 82.0, 46.0, 22.0 ],
                    "text": "r~ out1"
                }
            },
            {
                "box": {
                    "id": "obj-29",
                    "lastchannelcount": 0,
                    "maxclass": "live.gain~",
                    "numinlets": 2,
                    "numoutlets": 5,
                    "outlettype": [ "signal", "signal", "", "float", "list" ],
                    "parameter_enable": 1,
                    "patching_rect": [ 92.0, 299.0, 48.0, 136.0 ],
                    "saved_attribute_attributes": {
                        "valueof": {
                            "parameter_longname": "live.gain~[3]",
                            "parameter_mmax": 6.0,
                            "parameter_mmin": -70.0,
                            "parameter_modmode": 3,
                            "parameter_shortname": "live.gain~[3]",
                            "parameter_type": 0,
                            "parameter_unitstyle": 4
                        }
                    },
                    "varname": "live.gain~"
                }
            },
            {
                "box": {
                    "id": "obj-28",
                    "maxclass": "newobj",
                    "numinlets": 0,
                    "numoutlets": 0,
                    "patching_rect": [ 92.0, 767.0, 40.0, 22.0 ],
                    "text": "polish"
                }
            },
            {
                "box": {
                    "id": "obj-139",
                    "maxclass": "newobj",
                    "numinlets": 1,
                    "numoutlets": 0,
                    "patching_rect": [ 167.0, 736.0, 74.0, 22.0 ],
                    "text": "s~ fx-chain2"
                }
            },
            {
                "box": {
                    "id": "obj-138",
                    "maxclass": "newobj",
                    "numinlets": 1,
                    "numoutlets": 0,
                    "patching_rect": [ 93.0, 736.0, 74.0, 22.0 ],
                    "text": "s~ fx-chain1"
                }
            },
            {
                "box": {
                    "id": "obj-23",
                    "maxclass": "message",
                    "numinlets": 2,
                    "numoutlets": 1,
                    "outlettype": [ "" ],
                    "patching_rect": [ 374.0, 745.0, 78.15789484977722, 22.0 ],
                    "text": "sexy-move"
                }
            },
            {
                "box": {
                    "id": "obj-22",
                    "maxclass": "message",
                    "numinlets": 2,
                    "numoutlets": 1,
                    "outlettype": [ "" ],
                    "patching_rect": [ 317.0, 745.0, 50.0, 22.0 ],
                    "text": "B"
                }
            },
            {
                "box": {
                    "id": "obj-5",
                    "maxclass": "newobj",
                    "numinlets": 3,
                    "numoutlets": 3,
                    "outlettype": [ "", "", "" ],
                    "patching_rect": [ 348.0, 711.0, 188.63157868385315, 22.0 ],
                    "text": "route face algorithm"
                }
            },
            {
                "box": {
                    "id": "obj-15",
                    "maxclass": "newobj",
                    "numinlets": 1,
                    "numoutlets": 0,
                    "patching_rect": [ 262.0, 681.0, 145.0, 22.0 ],
                    "text": "udpsend 127.0.0.1 57122"
                }
            },
            {
                "box": {
                    "fontname": "Arial",
                    "fontsize": 12.0,
                    "id": "obj-19",
                    "maxclass": "message",
                    "numinlets": 2,
                    "numoutlets": 1,
                    "outlettype": [ "" ],
                    "patching_rect": [ 92.0, 681.0, 155.0, 22.0 ],
                    "text": "read xenakube_main.swam"
                }
            },
            {
                "box": {
                    "id": "obj-7",
                    "maxclass": "ezdac~",
                    "numinlets": 2,
                    "numoutlets": 0,
                    "patching_rect": [ 92.0, 490.0, 48.0, 48.0 ]
                }
            },
            {
                "box": {
                    "id": "obj-4",
                    "maxclass": "newobj",
                    "numinlets": 1,
                    "numoutlets": 1,
                    "outlettype": [ "bang" ],
                    "patching_rect": [ 92.0, 681.0, 58.0, 22.0 ],
                    "text": "loadbang"
                }
            },
            {
                "box": {
                    "id": "obj-21",
                    "maxclass": "button",
                    "numinlets": 1,
                    "numoutlets": 1,
                    "outlettype": [ "bang" ],
                    "parameter_enable": 0,
                    "patching_rect": [ 211.0, 595.0, 24.0, 24.0 ]
                }
            },
            {
                "box": {
                    "id": "obj-12",
                    "maxclass": "toggle",
                    "numinlets": 1,
                    "numoutlets": 1,
                    "outlettype": [ "int" ],
                    "parameter_enable": 0,
                    "patching_rect": [ 92.0, 538.0, 48.0, 48.0 ]
                }
            },
            {
                "box": {
                    "id": "obj-10",
                    "maxclass": "newobj",
                    "numinlets": 2,
                    "numoutlets": 1,
                    "outlettype": [ "" ],
                    "patching_rect": [ 92.0, 627.0, 32.0, 22.0 ],
                    "text": "gate"
                }
            },
            {
                "box": {
                    "filename": "xk_swam.js",
                    "id": "obj-2",
                    "maxclass": "newobj",
                    "numinlets": 1,
                    "numoutlets": 4,
                    "outlettype": [ "", "", "", "" ],
                    "patching_rect": [ 92.0, 654.0, 274.3589771389961, 22.0 ],
                    "saved_object_attributes": {
                        "parameter_enable": 0
                    },
                    "text": "v8 xk_swam.js @autowatch 1",
                    "textfile": {
                        "filename": "xk_swam.js",
                        "flags": 0,
                        "embed": 0,
                        "autowatch": 1
                    },
                    "varname": "v8"
                }
            },
            {
                "box": {
                    "id": "obj-1",
                    "maxclass": "newobj",
                    "numinlets": 1,
                    "numoutlets": 1,
                    "outlettype": [ "" ],
                    "patching_rect": [ 105.0, 596.0, 104.0, 22.0 ],
                    "text": "udpreceive 57121"
                }
            }
        ],
        "lines": [
            {
                "patchline": {
                    "destination": [ "obj-10", 1 ],
                    "order": 1,
                    "source": [ "obj-1", 0 ]
                }
            },
            {
                "patchline": {
                    "destination": [ "obj-21", 0 ],
                    "order": 0,
                    "source": [ "obj-1", 0 ]
                }
            },
            {
                "patchline": {
                    "destination": [ "obj-2", 0 ],
                    "source": [ "obj-10", 0 ]
                }
            },
            {
                "patchline": {
                    "destination": [ "obj-29", 0 ],
                    "source": [ "obj-11", 0 ]
                }
            },
            {
                "patchline": {
                    "destination": [ "obj-10", 0 ],
                    "order": 0,
                    "source": [ "obj-12", 0 ]
                }
            },
            {
                "patchline": {
                    "destination": [ "obj-7", 0 ],
                    "order": 1,
                    "source": [ "obj-12", 0 ]
                }
            },
            {
                "patchline": {
                    "destination": [ "obj-3", 0 ],
                    "source": [ "obj-19", 0 ]
                }
            },
            {
                "patchline": {
                    "destination": [ "obj-13", 0 ],
                    "source": [ "obj-2", 1 ]
                }
            },
            {
                "patchline": {
                    "destination": [ "obj-15", 0 ],
                    "source": [ "obj-2", 2 ]
                }
            },
            {
                "patchline": {
                    "destination": [ "obj-3", 0 ],
                    "source": [ "obj-2", 0 ]
                }
            },
            {
                "patchline": {
                    "destination": [ "obj-5", 0 ],
                    "source": [ "obj-2", 3 ]
                }
            },
            {
                "patchline": {
                    "destination": [ "obj-34", 0 ],
                    "order": 1,
                    "source": [ "obj-20", 0 ]
                }
            },
            {
                "patchline": {
                    "destination": [ "obj-8", 0 ],
                    "order": 0,
                    "source": [ "obj-20", 0 ]
                }
            },
            {
                "patchline": {
                    "destination": [ "obj-29", 1 ],
                    "source": [ "obj-26", 0 ]
                }
            },
            {
                "patchline": {
                    "destination": [ "obj-8", 0 ],
                    "source": [ "obj-27", 0 ]
                }
            },
            {
                "patchline": {
                    "destination": [ "obj-40", 1 ],
                    "order": 0,
                    "source": [ "obj-29", 1 ]
                }
            },
            {
                "patchline": {
                    "destination": [ "obj-40", 0 ],
                    "order": 0,
                    "source": [ "obj-29", 0 ]
                }
            },
            {
                "patchline": {
                    "destination": [ "obj-7", 1 ],
                    "order": 1,
                    "source": [ "obj-29", 1 ]
                }
            },
            {
                "patchline": {
                    "destination": [ "obj-7", 0 ],
                    "order": 1,
                    "source": [ "obj-29", 0 ]
                }
            },
            {
                "patchline": {
                    "destination": [ "obj-138", 0 ],
                    "source": [ "obj-3", 0 ]
                }
            },
            {
                "patchline": {
                    "destination": [ "obj-139", 0 ],
                    "source": [ "obj-3", 1 ]
                }
            },
            {
                "patchline": {
                    "destination": [ "obj-32", 0 ],
                    "source": [ "obj-33", 1 ]
                }
            },
            {
                "patchline": {
                    "destination": [ "obj-12", 0 ],
                    "source": [ "obj-34", 0 ]
                }
            },
            {
                "patchline": {
                    "destination": [ "obj-40", 0 ],
                    "midpoints": [ 312.5, 474.0, 234.5, 474.0 ],
                    "source": [ "obj-38", 0 ]
                }
            },
            {
                "patchline": {
                    "destination": [ "obj-40", 0 ],
                    "midpoints": [ 234.5, 432.0, 234.5, 432.0 ],
                    "source": [ "obj-39", 0 ]
                }
            },
            {
                "patchline": {
                    "destination": [ "obj-19", 0 ],
                    "source": [ "obj-4", 0 ]
                }
            },
            {
                "patchline": {
                    "destination": [ "obj-36", 0 ],
                    "source": [ "obj-40", 0 ]
                }
            },
            {
                "patchline": {
                    "destination": [ "obj-22", 1 ],
                    "source": [ "obj-5", 0 ]
                }
            },
            {
                "patchline": {
                    "destination": [ "obj-23", 1 ],
                    "source": [ "obj-5", 1 ]
                }
            },
            {
                "patchline": {
                    "destination": [ "obj-72", 0 ],
                    "source": [ "obj-66", 0 ]
                }
            },
            {
                "patchline": {
                    "destination": [ "obj-16", 0 ],
                    "source": [ "obj-72", 4 ]
                }
            },
            {
                "patchline": {
                    "destination": [ "obj-18", 0 ],
                    "source": [ "obj-72", 6 ]
                }
            },
            {
                "patchline": {
                    "destination": [ "obj-24", 0 ],
                    "source": [ "obj-72", 5 ]
                }
            },
            {
                "patchline": {
                    "destination": [ "obj-25", 0 ],
                    "source": [ "obj-72", 3 ]
                }
            },
            {
                "patchline": {
                    "destination": [ "obj-30", 0 ],
                    "source": [ "obj-72", 1 ]
                }
            },
            {
                "patchline": {
                    "destination": [ "obj-6", 0 ],
                    "source": [ "obj-72", 0 ]
                }
            },
            {
                "patchline": {
                    "destination": [ "obj-9", 0 ],
                    "source": [ "obj-72", 2 ]
                }
            },
            {
                "patchline": {
                    "destination": [ "obj-33", 0 ],
                    "source": [ "obj-8", 1 ]
                }
            }
        ],
        "parameters": {
            "obj-28::obj-16": [ "live.gain~[2]", "live.gain~", 0 ],
            "obj-28::obj-6": [ "live.gain~", "live.gain~", 0 ],
            "obj-28::obj-7": [ "vst~", "vst~", 0 ],
            "obj-29": [ "live.gain~[3]", "live.gain~[3]", 0 ],
            "obj-3": [ "vst~[1]", "vst~[1]", 0 ],
            "parameterbanks": {
                "0": {
                    "index": 0,
                    "name": "",
                    "parameters": [ "-", "-", "-", "-", "-", "-", "-", "-" ],
                    "buttons": [ "-", "-", "-", "-", "-", "-", "-", "-" ]
                }
            },
            "inherited_shortname": 1
        },
        "autosave": 0,
        "styles": [
            {
                "name": "rnbohighcontrast",
                "default": {
                    "accentcolor": [ 0.666666666666667, 0.666666666666667, 0.666666666666667, 1.0 ],
                    "bgcolor": [ 0.0, 0.0, 0.0, 1.0 ],
                    "bgfillcolor": {
                        "angle": 270.0,
                        "autogradient": 0.0,
                        "color": [ 0.0, 0.0, 0.0, 1.0 ],
                        "color1": [ 0.090196078431373, 0.090196078431373, 0.090196078431373, 1.0 ],
                        "color2": [ 0.156862745098039, 0.168627450980392, 0.164705882352941, 1.0 ],
                        "proportion": 0.5,
                        "type": "color"
                    },
                    "clearcolor": [ 1.0, 1.0, 1.0, 0.0 ],
                    "color": [ 1.0, 0.874509803921569, 0.141176470588235, 1.0 ],
                    "editing_bgcolor": [ 0.258823529411765, 0.258823529411765, 0.258823529411765, 1.0 ],
                    "elementcolor": [ 0.223386004567146, 0.254748553037643, 0.998085916042328, 1.0 ],
                    "fontsize": [ 13.0 ],
                    "locked_bgcolor": [ 0.258823529411765, 0.258823529411765, 0.258823529411765, 1.0 ],
                    "selectioncolor": [ 0.301960784313725, 0.694117647058824, 0.949019607843137, 1.0 ],
                    "stripecolor": [ 0.258823529411765, 0.258823529411765, 0.258823529411765, 1.0 ],
                    "textcolor": [ 1.0, 1.0, 1.0, 1.0 ],
                    "textcolor_inverse": [ 1.0, 1.0, 1.0, 1.0 ]
                },
                "parentstyle": "",
                "multi": 0
            }
        ]
    }
}