// === Kinematic Diagrams: Graph Paths through S4 (pp. 220-222) ===
//
// Xenakis specifies that transformations "follow various graphs (kinematic diagrams)
// inherent in the internal structure of this particular group."
//
// Two modes:
//   Direct: each physical cube turn maps directly to an S4 element
//   Diagram: pre-composed paths through S4 that the performer steps through

import type { GroupElement } from './types.js';
import { multiply, CAYLEY, ELEMENTS, IDENTITY, INVERSES } from './group.js';

/** A kinematic diagram is a sequence of group elements to traverse */
export interface KinematicDiagram {
  name: string;
  description: string;
  /** Sequence of group element indices forming the path */
  path: GroupElement[];
}

// === Pre-composed diagrams ===
// These are generated from the group structure itself.

/** Generate a diagram from repeated application of a single element (cyclic subgroup) */
function cyclicPath(generator: GroupElement): GroupElement[] {
  const path: GroupElement[] = [IDENTITY];
  let current = generator;
  while (current !== IDENTITY) {
    path.push(current);
    current = CAYLEY[current][generator];
  }
  return path;
}

/** Generate all elements reachable by multiplying two generators in alternation */
function alternatingPath(a: GroupElement, b: GroupElement, maxLen: number = 24): GroupElement[] {
  const path: GroupElement[] = [IDENTITY];
  const seen = new Set<number>([IDENTITY]);
  let current: GroupElement = IDENTITY;
  let useA = true;

  for (let i = 0; i < maxLen; i++) {
    current = CAYLEY[current][useA ? a : b];
    if (seen.has(current)) break;
    seen.add(current);
    path.push(current);
    useA = !useA;
  }

  return path;
}

/** Build a Hamiltonian-style path visiting all 24 elements (greedy DFS) */
function hamiltonianPath(): GroupElement[] {
  // Use 3 generators that produce the full group
  // Find them: elements of order 2, 3, and 4
  const orders: Map<number, GroupElement[]> = new Map();
  for (let i = 1; i < 24; i++) {
    let order = 1;
    let current = i;
    while (current !== IDENTITY) {
      current = CAYLEY[current][i];
      order++;
      if (order > 24) break;
    }
    if (!orders.has(order)) orders.set(order, []);
    orders.get(order)!.push(i);
  }

  // Greedy DFS to visit all 24 elements
  const visited = new Set<number>([IDENTITY]);
  const path: GroupElement[] = [IDENTITY];

  // Get all non-identity elements as potential next steps
  const generators = Array.from({ length: 23 }, (_, i) => i + 1);

  while (path.length < 24) {
    const current = path[path.length - 1];
    let found = false;

    for (const gen of generators) {
      const next = CAYLEY[current][gen];
      if (!visited.has(next)) {
        visited.add(next);
        path.push(next);
        found = true;
        break;
      }
    }

    if (!found) break; // stuck (shouldn't happen with full group)
  }

  return path;
}

/** Built-in kinematic diagrams */
export function getBuiltinDiagrams(): KinematicDiagram[] {
  const diagrams: KinematicDiagram[] = [];

  // Cyclic subgroups from elements of various orders
  for (let i = 1; i < 24; i++) {
    const path = cyclicPath(i);
    if (path.length > 2 && path.length <= 6) {
      diagrams.push({
        name: `cyclic_${i}_order${path.length}`,
        description: `Cyclic subgroup of order ${path.length} generated by element ${i}`,
        path,
      });
    }
  }

  // Full traversal
  diagrams.push({
    name: 'hamiltonian',
    description: 'Path visiting all 24 group elements',
    path: hamiltonianPath(),
  });

  return diagrams;
}

/** Kinematic diagram traversal state */
export class DiagramTraversal {
  private diagram: KinematicDiagram;
  private position: number = 0;

  constructor(diagram: KinematicDiagram) {
    this.diagram = diagram;
  }

  /** Get current element in the diagram */
  current(): GroupElement {
    return this.diagram.path[this.position];
  }

  /** Advance one step, return the new element. Wraps around. */
  advance(): GroupElement {
    this.position = (this.position + 1) % this.diagram.path.length;
    return this.diagram.path[this.position];
  }

  /** Go back one step */
  retreat(): GroupElement {
    this.position = (this.position - 1 + this.diagram.path.length) % this.diagram.path.length;
    return this.diagram.path[this.position];
  }

  /** Reset to start */
  reset(): void {
    this.position = 0;
  }

  /** Get position info */
  getPosition(): { index: number; total: number } {
    return { index: this.position, total: this.diagram.path.length };
  }
}
